package:
  name: "jemalloc"
  version: "5.1.0"

source:
  fn: "jemalloc-5.1.0.tar.bz2"
  url:
    - "https://github.com/jemalloc/jemalloc/releases/download/5.1.0/jemalloc-5.1.0.tar.bz2"
  md5: "1f47a5aff2d323c317dfa4cf23be1ce4"

build:
  number: 0
  script_env:
    - BB_MAKE_JOBS

about:
  home: "https://github.com/jemalloc/jemalloc"
  license: BSD
  license_file: COPYING
  summary: "General purpose malloc(3) implementation that emphasizes fragmentation avoidance and scalable concurrency support"
