{% set version = "0.2-15" %}

package:
  name: r-codetools
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-codetools_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/codetools_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/codetools/codetools_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-codetools_{{ version }}.tar.gz"
  sha256: "4e0798ed79281a614f8cdd199e25f2c1bd8f35ecec902b03016544bd7795fa40"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base=3.6.1

  run:
    - r-base

test:
  commands:
    - $R -e "library('codetools')" # [not win]
    - "\"%R%\" -e \"library('codetools')\"" # [win]

about:
  license: GPL
  summary: Code analysis tools for R


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: codetools
# Version: 0.2-15
# Priority: recommended
# Author: Luke Tierney <luke-tierney@uiowa.edu>
# Description: Code analysis tools for R.
# Title: Code Analysis Tools for R
# Depends: R (>= 2.1)
# Maintainer: Luke Tierney <luke-tierney@uiowa.edu>
# License: GPL
# NeedsCompilation: no
# Packaged: 2016-10-05 12:32:32 UTC; luke
# Repository: CRAN
# Date/Publication: 2016-10-05 16:36:47
#----------------------------------------------------------------------
