{% set name = "glue" %}
{% set version = "1.2.0" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "19275b34ee6a1bcad05360b7eb996cebaa1402f189a5dfb084e695d423f2296e"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

# Suggests: testthat, covr, magrittr, crayon, knitr, rmarkdown, DBI, RSQLite, R.utils, forcats, microbenchmark, rprintf, stringr, ggplot2
requirements:
  build:
    - r-base {{ r_base }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://github.com/tidyverse/glue
  license: MIT
  license_family: MIT
  summary: Interpreted string literals
  description: |
    An implementation of interpreted string literals, inspired by Python's
    literal string interpolation and docstrings, and Julia's triple-quoted
    string literals.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: glue
# Title: Interpreted String Literals
# Version: 1.2.0
# Authors@R: person("Jim", "Hester", email = "james.f.hester@gmail.com", role = c("aut", "cre"))
# Description: An implementation of interpreted string literals, inspired by Python's Literal String Interpolation <https://www.python.org/dev/peps/pep-0498/> and Docstrings <https://www.python.org/dev/peps/pep-0257/> and Julia's Triple-Quoted String Literals <https://docs.julialang.org/en/stable/manual/strings/#triple-quoted-string-literals>.
# Depends: R (>= 3.1)
# Suggests: testthat, covr, magrittr, crayon, knitr, rmarkdown, DBI, RSQLite, R.utils, forcats, microbenchmark, rprintf, stringr, ggplot2
# Imports: methods
# License: MIT + file LICENSE
# Encoding: UTF-8
# LazyData: true
# RoxygenNote: 6.0.1
# URL: https://github.com/tidyverse/glue
# BugReports: https://github.com/tidyverse/glue/issues
# VignetteBuilder: knitr
# ByteCompile: true
# NeedsCompilation: yes
# Packaged: 2017-10-29 19:05:15 UTC; jhester
# Author: Jim Hester [aut, cre]
# Maintainer: Jim Hester <james.f.hester@gmail.com>
# Repository: CRAN
# Date/Publication: 2017-10-29 20:03:53 UTC
#----------------------------------------------------------------------
