package:
  name: perl-file-sort
  version: "1.01"

source:
  url: http://cpan.metacpan.org/authors/id/C/CN/CNANDOR/File-Sort-1.01.tar.gz
  md5: 1feb4128bba2edde68ada7838e55863a

build:
  noarch: generic
  number: 2

requirements:
  host:
    - perl==5.26.2

  run:
    - perl==5.26.2

test:
  # Perl 'use' tests
  imports:
    - File::Sort

about:
  home: http://metacpan.org/pod/File-Sort
  license: unknown
  summary: 'Sort a file or merge sort multiple files'
