{% set maj_min = "1.9" %}
{% set patch = "0" %}
{% set version = maj_min ~ "." ~ patch %}

package:
  name: samtools
  version: "{{ version }}"

source:
  fn: "htslib-{{ version }}.tar.bz2"
  url:
    - "https://github.com/samtools/samtools/releases/download/{{ maj_min }}/samtools-{{ maj_min }}.tar.bz2"
  sha256: "083f688d7070082411c72c27372104ed472ed7a620591d06f928e653ebc23482"

requirements:
  # TODO: get curses support working; currently, attempting to build with
  # ncurses leads to a bunch of undeclared name and unknown type errors.
  build:
    - biobuilds-build
    - zlib 1.2.11
    #- ncurses {{ ncurses }}
    - htslib 1.9.0
  run:
    - zlib
    #- ncurses
    - htslib 1.9.0
    - python
    - perl 5.*

build:
  number: 0
  detect_binary_files_with_prefix: true
  features:
    - opt                       # [toolchain != 'default']

test:
  requires:
    - biobuilds-opt             # [toolchain != 'default']
  commands:
    # Bulk of tests are performed in the build process. This basically just
    # ensures we got our Perl requirement correct.
    - "samtools --help >/dev/null"

about:
  home: http://www.htslib.org/
  license: MIT
  license_file: LICENSE
  summary: "Various utilities for manipulating alignments in the SAM/BAM format"
