package:
  name: perl-lwp-simple
  version: '6.15'

source:
  url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/libwww-perl-6.15.tar.gz
  sha256: 6f349d45c21b1ec0501c4437dfcb70570940e6c3d5bff783bd91d4cddead8322

build:
  number: 4
  noarch: generic

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl==5.26.2
    - perl-encode-locale
    - perl-module-build
    - perl-net-http
    - perl-html-parser
    - perl-uri
    - perl-http-cookies
    - perl-http-date
    - perl-libwww-perl==6.15

  run:
    - perl==5.26.2
    - perl-encode-locale
    - perl-net-http
    - perl-html-parser
    - perl-uri
    - perl-http-cookies
    - perl-http-date
    - perl-libwww-perl==6.15

test:
  imports:
    - LWP::Simple

about:
  home: https://metacpan.org/pod/LWP::Simple
  license: Perl
  summary: simple procedural interface to LWP
