package:
  name: bioconductor-s4vectors
  version: "0.8.3"

source:
  fn: S4Vectors_0.8.3.tar.gz
  url: "https://bioconductor.org/packages/3.2/bioc/src/contrib/S4Vectors_0.8.3.tar.gz"
  md5: 16f87e21d7903f986e1ac5cee3cac271

requirements:
  build:
    - r-base
    - gcc  # [not ppc64le]
    - bioconductor-biocgenerics >=0.15.10
  run:
    - r-base
    - libgcc  # [not ppc64le]
    - bioconductor-biocgenerics >=0.15.10

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('S4Vectors')"  # [not win]
    - "\"%R%\" -e \"library('S4Vectors')\""  # [win]

about:
  home: "https://www.bioconductor.org/packages/release/bioc/html/S4Vectors.html"
  license: Artistic 2.0
  summary: "S4 implementation of vectors and lists"
