{% set name = "perl-b" %}
{% set version = "1.48" %}
{% set sha256 = "" %}

package:
  name: {{ name }}
  version: {{ version }}

build:
  noarch: generic
  number: 1

requirements:
  build:
    - perl==5.26.2

  run:
    - perl==5.26.2

about:
  home: http://metacpan.org/pod/B
  license: perl_5
  summary: 'The Perl Compiler Backend'
