package:
    name: multiqc
    version: '1.8'
source:
    patches:
        - patch
    sha256: 8d2ae93bd2b9e58db11f7453462f0b41bd21e8c751e7b522dc7e32ff73b78ea9
    url: https://github.com/ewels/MultiQC/archive/v1.8.tar.gz
build:
    entry_points:
        - multiqc=multiqc.__main__:multiqc
    noarch: python
    number: '2'
    preserve_egg_dir: true
    string: py_2
requirements:
    host:
        - ca-certificates 2019.11.28 hecc5488_0
        - certifi 2019.11.28 py27_0
        - libffi 3.2.1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1d
        - pip 20.0.2 py_2
        - python 2.7.15 h653d3de_1009
        - readline 8.0 hf8c457e_0
        - setuptools 44.0.0 py27_0
        - sqlite 3.30.1
        - tk 8.6.10
        - wheel 0.34.2 py_1
        - zlib 1.2.11 
    run:
        - click
        - coloredlogs
        - future >0.14.0
        - jinja2 >=2.9
        - lzstring
        - markdown
        - matplotlib-base >=2.1.1,<3.1.2
        - networkx <2.3
        - numpy
        - python
        - pyyaml >=4
        - requests
        - setuptools
        - simplejson
        - spectra >=0.0.10
test:
    commands:
        - multiqc --version
        - multiqc .
    imports:
        - multiqc
        - multiqc.modules
        - multiqc.modules.adapterRemoval
        - multiqc.modules.afterqc
        - multiqc.modules.bamtools
        - multiqc.modules.bbmap
        - multiqc.modules.bcftools
        - multiqc.modules.bcl2fastq
        - multiqc.modules.biobambam2
        - multiqc.modules.biobloomtools
        - multiqc.modules.biscuit
        - multiqc.modules.bismark
        - multiqc.modules.bowtie1
        - multiqc.modules.bowtie2
        - multiqc.modules.busco
        - multiqc.modules.clipandmerge
        - multiqc.modules.clusterflow
        - multiqc.modules.conpair
        - multiqc.modules.custom_content
        - multiqc.modules.cutadapt
        - multiqc.modules.damageprofiler
        - multiqc.modules.dedup
        - multiqc.modules.deeptools
        - multiqc.modules.disambiguate
        - multiqc.modules.fastp
        - multiqc.modules.fastq_screen
        - multiqc.modules.fastqc
        - multiqc.modules.featureCounts
        - multiqc.modules.fgbio
        - multiqc.modules.flash
        - multiqc.modules.flexbar
        - multiqc.modules.gatk
        - multiqc.modules.goleft_indexcov
        - multiqc.modules.happy
        - multiqc.modules.hicexplorer
        - multiqc.modules.hicpro
        - multiqc.modules.hicup
        - multiqc.modules.hisat2
        - multiqc.modules.homer
        - multiqc.modules.htseq
        - multiqc.modules.interop
        - multiqc.modules.jellyfish
        - multiqc.modules.kallisto
        - multiqc.modules.kat
        - multiqc.modules.leehom
        - multiqc.modules.longranger
        - multiqc.modules.macs2
        - multiqc.modules.methylQA
        - multiqc.modules.minionqc
        - multiqc.modules.mirtrace
        - multiqc.modules.mosdepth
        - multiqc.modules.mtnucratio
        - multiqc.modules.peddy
        - multiqc.modules.phantompeakqualtools
        - multiqc.modules.picard
        - multiqc.modules.preseq
        - multiqc.modules.prokka
        - multiqc.modules.qorts
        - multiqc.modules.qualimap
        - multiqc.modules.quast
        - multiqc.modules.rna_seqc
        - multiqc.modules.rsem
        - multiqc.modules.rseqc
        - multiqc.modules.salmon
        - multiqc.modules.samblaster
        - multiqc.modules.samtools
        - multiqc.modules.sargasso
        - multiqc.modules.seqyclean
        - multiqc.modules.sexdeterrmine
        - multiqc.modules.skewer
        - multiqc.modules.slamdunk
        - multiqc.modules.snpeff
        - multiqc.modules.sortmerna
        - multiqc.modules.stacks
        - multiqc.modules.star
        - multiqc.modules.supernova
        - multiqc.modules.theta2
        - multiqc.modules.tophat
        - multiqc.modules.trimmomatic
        - multiqc.modules.vcftools
        - multiqc.modules.verifybamid
        - multiqc.plots
        - multiqc.templates
        - multiqc.templates.default
        - multiqc.templates.default_dev
        - multiqc.templates.geo
        - multiqc.templates.sections
        - multiqc.templates.simple
        - multiqc.utils
about:
    dev_url: https://github.com/ewels/MultiQC
    doc_url: http://multiqc.info/docs/
    home: http://multiqc.info
    license: GNU General Public License v3 (GPLv3)
    license_family: GPL3
    license_file: LICENSE
    summary: Create aggregate bioinformatics analysis reports across many samples
        and tools
extra:
    container:
        extended-base: true
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:multiqc
        - doi:https://doi.org/10.1093/bioinformatics/btw354
    skip-lints:
        - uses_setuptools
