package:
  name: bioconductor-biocparallel
  version: "1.8.1"

source:
  fn: "BiocParallel_1.8.1.tar.gz"
  url: "https://bioconductor.org/packages/release/bioc/src/contrib/BiocParallel_1.8.1.tar.gz"
  md5: "73fe5916e67c3ff4fbee15cbd5c02f0a"

requirements:
  build:
    - r-base
    - r-futile.logger
    - r-snow
  run:
    - r-base
    - r-futile.logger
    - r-snow

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('BiocParallel')"            # [not win]
    - "\"%R%\" -e \"library('BiocParallel')\""   # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/BiocParallel.html"
  license: "Artistic 2.0"
  summary: "Bioconductor facilities for parallel evaluation"
