{% set version = "3.5.1" %}

package:
  name: r-base
  version: "{{ version }}"

source:
  fn: "R-{{ version }}.tar.gz"
  url:
    - "https://cran.r-project.org/src/base/R-3/R-{{ version }}.tar.gz"
  sha256: "0463bff5eea0f3d93fa071f79c18d0993878fd4f2e18ae6cf22c1639d11457ed"
build:
  skip: True  # [win]
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - biobuilds-build
    # Compression libraries
    # Graphics libraries
  run:
    # Commented-out ones should be handled by the package's 'run_exports'
    #- readline
    #- icu
    #- curl
    #- gsl
    #- pcre
    #- libxml2
    #- bzip2
    #- xz
    #- zlib
    #- jpeg
    #- libpng
    #- libtiff
    #- cairo     # [linux]
    #- pango     # [linux]
    #- tk        # [linux]

test:
  commands:
    - R -h
    - R --version
    - Rscript --version
    - Rscript -e 'cat("ok\\n")'
    # Verify tcltk.so linking so bug #14 (BIOBUILDS-335) does not reoccur.
    - Rscript -e 'library("tcltk")'   # [linux]

about:
  home: http://www.r-project.org/
  license: GPLv2
  license_file: COPYING
  summary: "Base binaries for the R statistical computing environment. You should install the 'r-recommended' package as well."

extra:
  recipe-maintainers:
    - bgruening
    - johanneskoester
    - mingwandroid
    - ocefpaf
    - sodre
    - chenghlee
