package:
  name: freebayes
  version: '1.3.2'

source:
  git_url: https://github.com/ekg/freebayes.git
  git_tag: 54bf40915ae7e46798503471ac57f593efdb5493
  patches:
    - qcfail.diff

build:
  number: 2
  string: hpda0720_2

requirements:
  build:
    - {{ compiler('c') }}
    - {{ compiler('cxx') }}
  host:
    - perl==5.26.2
    - zlib
    - bzip2
    - parallel
    - python==3.7.6
    - xz
  run:
    - perl==5.26.2
    - zlib
    - bzip2
    - python==3.7.6
    - htslib==1.10.2
    - parallel
    - xz
test:
  commands:
    - freebayes --version
    - vcfstreamsort -h
    - bamleftalign -h

about:
  home: https://github.com/ekg/freebayes
  license: MIT
  license_file: LICENSE
  license_family: MIT
  summary: Bayesian haplotype-based polymorphism discovery and genotyping
  maintainers: jpuritz

extra:
  skip-lints:
    - missing_hash
    - uses_vcs_url
  identifiers:
    - biotools:freebayes
