{% set name = "Rsamtools" %}
{% set version = "1.34.1" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://bioconductor.org/packages/3.8/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
  sha256: '69721af56d241b355f16e66b6799f5436aeceb5db55eb48253b32d45e7c1ea0a'

requirements:
  build:
    - r-base {{ r_base }}
    - bioconductor-biocparallel
    - bioconductor-genomeinfodb >=1.1.3
    - bioconductor-genomicranges >=1.21.6
    - bioconductor-biostrings >=2.37.1
  run:
    - r-base
    - bioconductor-biocparallel
    - bioconductor-genomeinfodb >=1.1.3
    - bioconductor-genomicranges >=1.21.6
    - bioconductor-biostrings >=2.37.1

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: Binary alignment (BAM), FASTA, variant call (BCF), and tabix file import
  description: |
     Interface to the "samtools", "bcftools", and "tabix" utilities (see
     "LICENCE") for manipulating SAM (Sequence Alignment / Map), FASTA, binary
     variant call (BCF) and compressed indexed tab-delimited (tabix) files.
