# This file created by conda-build 3.18.9
# meta.yaml template originally from:
# /opt/recipe, last modified Mon Aug  5 14:21:09 2019
# ------------------------------------------------

package:
    name: tiddit
    version: 2.7.1
source:
    sha256: 1d014cd2d4e1f5410e9ffbeda7a0512d65895ec38d57e8aed5dffa19f32f4699
    url: https://github.com/SciLifeLab/TIDDIT/archive/TIDDIT-2.7.1.tar.gz
build:
    number: '1'
    string: py27hb3f55d8_1
requirements:
    build:
        - _libgcc_mutex 0.1 main
        - binutils_impl_linux-64 2.31.1 h6176602_1
        - binutils_linux-64 2.31.1 h6176602_7
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - cmake 3.15.0 hf94ab9c_0
        - curl 7.65.3 hf8cf82a_0
        - expat 2.2.5 he1b5a44_1003
        - gcc_impl_linux-64 7.3.0 habb00fd_1
        - gcc_linux-64 7.3.0 h553295d_7
        - gxx_impl_linux-64 7.3.0 hdf63c60_1
        - gxx_linux-64 7.3.0 h553295d_7
        - krb5 1.16.3 h05b26f9_1001
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libgcc-ng 9.1.0 hdf63c60_0
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.30.1 h516909a_0
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1c h516909a_0
        - rhash 1.3.6 h14c3975_1001
        - tk 8.6.9 hed695b0_1002
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    host:
        - _libgcc_mutex 0.1 main
        - bzip2 1.0.8 h516909a_0
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_1
        - cmake 3.15.0 hf94ab9c_0
        - curl 7.65.3 hf8cf82a_0
        - cython 0.29.13 py27he1b5a44_0
        - expat 2.2.5 he1b5a44_1003
        - krb5 1.16.3 h05b26f9_1001
        - libblas 3.8.0 11_openblas
        - libcblas 3.8.0 11_openblas
        - libcurl 7.65.3 hda55be3_0
        - libedit 3.1.20170329 hf8c457e_1001
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 9.1.0 hdf63c60_0
        - libgfortran-ng 7.3.0 hdf63c60_0
        - liblapack 3.8.0 11_openblas
        - libopenblas 0.3.6 h6e990d7_6
        - libssh2 1.8.2 h22169c7_2
        - libstdcxx-ng 9.1.0 hdf63c60_0
        - libuv 1.30.1 h516909a_0
        - ncurses 6.1 hf484d3e_1002
        - numpy 1.14.6 py27he5ce36f_1201
        - openssl 1.1.1c h516909a_0
        - pip 19.2.1 py27_0
        - python 2.7.15 h5a48372_1009
        - readline 8.0 hf8c457e_0
        - rhash 1.3.6 h14c3975_1001
        - setuptools 41.0.1 py27_0
        - sqlite 3.29.0 hcee41ef_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py27_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h516909a_1005
    run:
        - cmake
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
        - numpy
        - pysam
        - python >=2.7,<2.8.0a0
test:
    commands:
        - tiddit >/dev/null
about:
    home: https://github.com/SciLifeLab/TIDDIT
    license: GPL-3
    license_file: /opt/recipe/LICENSE
    summary: TIDDIT - structural variant calling.
extra:
    copy_test_source_files: true
    final: true
