{% set name = "perl-attribute-handlers" %}
{% set version = "0.96" %}
{% set sha256 = "" %}

package:
  name: {{ name }}
  version: {{ version }}
build:
  noarch: generic
  number: 2

requirements:
  build:
    - perl==5.26.2

  run:
    - perl==5.26.2

test:
  commands:
    - perl -e "use Attribute::Handlers"

about:
  home: http://metacpan.org/pod/Attribute::Handlers
  license: perl_5
  summary: 'Simpler definition of attribute handlers'
