{% set name = "samtools" %}
{% set version = "0.1.19" %}
{% set sha256 = "d080c9d356e5f0ad334007e4461cbcee3c4ca97b8a7a5a48c44883cf9dee63d4" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - zlib {{ zlib }}
  run:
    - perl==5.26.2

source:
  fn: "{{ name|lower }}-{{ version }}.tar.bz2"
  url:
    - "https://downloads.sourceforge.net/project/samtools/samtools/{{ version }}/samtools-{{ version }}.tar.bz2"
    - "http://download.lab7.io/sources/{{ name|lower }}-{{ version }}_{{ sha256[:10] }}.tar.bz2"
  sha256: "{{ sha256 }}"
  patches:
    - samtools-makefiles.patch
    - samtools-sources.patch

build:
  number: 1

test:
  files:
    - test.sam
  commands:
    - samtools view -bS test.sam > test.bam
    - samtools sort test.bam test.sorted
    # Need this because above returns 0 even if something failed
    - test -f test.sorted.bam

about:
  home: http://samtools.sourceforge.net/
  license: MIT
  license_file: COPYING
  summary: "Various utilities for manipulating alignments in the SAM/BAM format"
