{% set name = "GenomeInfoDb" %}
{% set version = "1.18.2" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "https://bioconductor.org/packages/{{ bioc_version }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "b72c73729779a69642d5ff593d04f9687c2416f1f38d05aeeafe7ec66419751d"

requirements:
  build:
    - r-base {{ r_base }}
    - r-rcurl
    - bioconductor-biocgenerics >=0.13.8
    - bioconductor-s4vectors >=0.9.25
    - bioconductor-iranges >=1.99.26
    - bioconductor-genomeinfodbdata
  run:
    - r-base=3.6.1
    - r-rcurl
    - bioconductor-biocgenerics >=0.13.8
    - bioconductor-s4vectors >=0.9.25
    - bioconductor-iranges >=1.99.26
    - bioconductor-genomeinfodbdata

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: Utilities for manipulating chromosome and other seqname identifiers
  description: |
    Contains data and functions that define and allow translation between
    different chromosome sequence naming conventions (e.g., "chr1" versus "1"),
    including a function that attempts to place sequence names in their
    natural, rather than lexicographic, order.
