{% set name = "EBSeq" %}
{% set version = "1.22.1" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://bioconductor.org/packages/{{ bioc_version }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
  sha256: "a0a9b5dffd4c6192174e60598939c0516fe7b34708aa3082045635be6098ebbf"

requirements:
  build:
    - r-base {{ r_base }}
    - r-blockmodeling
    - r-gplots
    - r-testthat
  run:
    - r-base
    - r-blockmodeling
    - r-gplots
    - r-testthat

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('EBSeq')"            # [not win]
    - "\"%R%\" -e \"library('EBSeq')\""   # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: "R package for gene and isoform differential expression analysis of RNA-seq data"
