package: 
  name: cloog
  version: 0.18.0
requirements:
  build: 
    - gmp >=5.0.2
    - isl
  run: 
    - gmp
    - isl
source:
  fn: cloog-0.18.0.tar.gz
  url: http://www.bastoul.net/cloog/pages/download/count.php3?url=./cloog-0.18.0.tar.gz
  patches: ppc64le.patch
test:
  commands:
  files: 
  imports:
  requires:
