package:
  name: perl-io-gzip
  version: "0.20"

source:
  url: https://cpan.metacpan.org/authors/id/N/NW/NWCLARK/PerlIO-gzip-0.20.tar.gz
  md5: 0393eae5d0b23df6cf40ed44af7d711c

build:
  noarch: generic
  number: 2

requirements:
  host:
    - perl==5.26.2
    - zlib
  run:
    - perl==5.26.2
    - zlib

test:
  # Perl 'use' tests
  imports:
    - PerlIO::gzip

about:
  home: https://metacpan.org/pod/PerlIO::gzip
  license: perl_5
  summary: 'Perl extension to provide a PerlIO layer to gzip/gunzip'
