package:
    name: cnvkit
    version: 0.9.6
source:
    sha256: c6f20e7cf22b20c81325f7cd55d4a8c835b37b1227f274386a6cc48450be9acd
    url: https://github.com/etal/cnvkit/archive/v0.9.6.tar.gz
    patches: power_python.patch
build:
    number: '1'
    string: py37_1
requirements:
    host:
        - bzip2 1.0.8
        - ca-certificates 2020.6.20
        - certifi 2020.6.20 py37hc8dfbb8_0
        - libffi 3.2.1
        - ncurses 6.2
        - openssl 1.1.1g
        - pandas 1.0.5 py37he1dd5e6_0
        - python 3.7.6
        - readline 8.0
        - setuptools 49.2.0
        - sqlite 3.32.3
        - tk 8.6.10
        - xz 5.2.5
        - zlib 1.2.11
    run:
        - bioconductor-dnacopy
        - biopython >=1.62
        - future >=0.18.2
        - matplotlib >=1.3.1
        - numpy >=1.9
        - pandas >=0.22.0
        - pomegranate >=0.9.0
        - pyfaidx >=0.4.7
        - pysam >=0.15.4
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.5.0
        - r-base >=3.6.1
        - r-cghflasso
        - reportlab >=3.0
        - scipy >=0.15.0
        - libopenblas
test:
    commands:
        - cnvkit.py -h
    imports:
        - cnvlib
        - skgenome
about:
    home: https://github.com/etal/cnvkit
    license: Apache License 2.0
    summary: Copy number variant detection from high-throughput sequencing
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:cnvkit
        - doi:10.1371/journal.pcbi.1004873
