package:
  name: hdf5
  version: "1.10.5"

source:
  fn: hdf5-1.10.5.tar.bz2
  url: https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.10/hdf5-1.10.5/src/hdf5-1.10.5.tar.bz2
  md5: "7c19d6b81ee2a3ba7d36f6922b2f90d3"

requirements:
  # Require gcc & libgcc to guarantee support for the FORTRAN and C++ libraries
  build:
    - autoconf-update
    - gcc     # [not ppc64le]
    - zlib
  run:
    - libgcc  # [not ppc64le]
    - zlib

build:
  number: 0
  script_env:
    - BB_ARCH_FLAGS
    - BB_OPT_FLAGS
    - BB_MAKE_JOBS

about:
  home: http://www.hdfgroup.org/HDF5/
  license: BSD-like (http://www.hdfgroup.org/ftp/HDF5/current/src/unpacked/COPYING)
  summary: Data model, library, and file format for storing and managing data
