package:
  name: perl-estscan1
  version: "1.3"

source:
  url: https://sourceforge.net/projects/estscan/files/ESTScan1/1.3/ESTScan1-1.3.tar.gz
  md5: 457e695657544d56e38b340ef3ebc46c

build:
  number: 1

requirements:
  build:
    - perl==5.26.2

  run:
    - perl==5.26.2
    - perl-btlib

test:
  # Perl 'use' tests
  imports:
    - ESTScan1
  commands:
    - perl -e 'use ESTScan1; my @mat = ESTScan1::LoadMatrix("HumanIso.smat", "CODING", 4.0);'

about:
  home: http://estscan.sourceforge.net
  license: 'open source'
  summary: 'Detects coding regions in DNA sequences even if they are of low quality.
    ESTScan.pm contains the Perl part of the code that reads in the matrices file.
    The C code that does the actual computation is located in estscan.c.'
