{% set name = "GATK" %}
{% set version = "4.5.0.0" %}
{% set sha256 = "2e0c3804df01e0d673eb31faac90c8fb63540ed85c6e2012d95bb21264419341" %}

package:
  name: {{ name|lower }}
  version: '{{ version }}'

source:
  url: file:///tmp/gatk-4.5.0.0-26-gb0ac604-SNAPSHOT.zip
  sha256: {{ sha256 }}

build:
  noarch: generic
  number: 0
  detect_binary_files_with_prefix: False

requirements:
  host:
  run:
    - openjdk >=17,<18
    - python

test:
  commands:
    - gatk -h
    - gatk --list
    - gatk HaplotypeCaller --help
    - gatk DetermineGermlineContigPloidy --help

about:
  home: https://www.broadinstitute.org/gatk/
  license: BSD-3-Clause
  license_family: BSD
  summary: Genome Analysis Toolkit (GATK4)
  dev_url: https://github.com/broadinstitute/gatk
