{% set name = "tibble" %}
{% set version = "1.3.4" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
  sha256: "a7eef7018a68fc07c17c583fb7821a08d6bc381f5961258bffaa6ef6b137760b"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

requirements:
  build:
    - r-base {{ r_base }}
    - r-rcpp >=0.12.3
    - r-rlang

  run:
    - r-base
    - r-rcpp >=0.12.3
    - r-rlang

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: http://tibble.tidyverse.org/, https://github.com/tidyverse/tibble
  license: MIT
  summary: Simple data frames for R
  description: |
    Provides a 'tbl_df' class (the 'tibble') that provides stricter checking
    and better formatting than the traditional data frame.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: tibble
# Encoding: UTF-8
# Version: 1.3.4
# Title: Simple Data Frames
# Description: Provides a 'tbl_df' class (the 'tibble') that provides stricter checking and better formatting than the traditional data frame.
# Authors@R: c( person("Kirill", "Muller", , "krlmlr+r@mailbox.org", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("Romain", "Francois", , "romain@r-enthusiasts.com", "ctb"), person("RStudio", role = "cph") )
# URL: http://tibble.tidyverse.org/, https://github.com/tidyverse/tibble
# BugReports: https://github.com/tidyverse/tibble/issues
# Depends: R (>= 3.1.0)
# Imports: methods, rlang, Rcpp (>= 0.12.3), utils
# Suggests: covr, dplyr, knitr (>= 1.5.32), microbenchmark, nycflights13, testthat, rmarkdown, withr
# LinkingTo: Rcpp
# LazyData: yes
# License: MIT + file LICENSE
# RoxygenNote: 6.0.1
# VignetteBuilder: knitr
# NeedsCompilation: yes
# Packaged: 2017-08-21 16:04:36 UTC; muelleki
# Author: Kirill Muller [aut, cre], Hadley Wickham [aut], Romain Francois [ctb], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-08-22 07:16:29 UTC
#----------------------------------------------------------------------
