{% set name = "GenomicAlignments" %}
{% set version = "1.18.1" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://bioconductor.org/packages/3.8/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
  sha256: '4d8a103c7e053a6a05b7a7cc5ee2c931d8280c529c5a01bf979c8c2cb6a25ad5'

requirements:
  build:
    - r-base {{ r_base }}
    - bioconductor-biocgenerics >=0.15.3
    - bioconductor-s4vectors >=0.13.13
    - bioconductor-iranges >=2.11.16
    - bioconductor-genomeinfodb >=1.13.1
    - bioconductor-genomicranges >=1.29.14
    - bioconductor-summarizedexperiment >=1.5.3
    - bioconductor-biostrings >=2.37.1
    - bioconductor-rsamtools >=1.21.4
  run:
    - r-base
    - bioconductor-biocgenerics >=0.15.3
    - bioconductor-s4vectors >=0.13.13
    - bioconductor-iranges >=2.11.16
    - bioconductor-genomeinfodb >=1.13.1
    - bioconductor-genomicranges >=1.29.14
    - bioconductor-summarizedexperiment >=1.5.3
    - bioconductor-biostrings >=2.37.1
    - bioconductor-rsamtools >=1.21.4

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/GenomicAlignments.html"
  license: "Artistic 2.0"
  summary: "Representation and manipulation of short genomic alignments"
  description: |
    Provides efficient containers for storing and manipulating short genomic
    alignments (typically obtained by aligning short reads to a reference
    genome).  This includes read counting, computing the coverage, junction
    detection, and working with the nucleotide content of the alignments.
