{% set version = "1.0.3" %}
{% set name = "tximeta" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
  sha256: 485566c4c67c910d4b9bd2b9713a2279e26bb5d80e445b47face060b936add81
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, testthat, tximportData, org.Dm.eg.db, DESeq2, edgeR, devtools
requirements:
  host:
    - 'bioconductor-annotationdbi >=1.44.0,<1.47.0'
    - 'bioconductor-biocfilecache >=1.6.0,<1.9.0'
    - 'bioconductor-biostrings >=2.50.0,<2.53.0'
    - 'bioconductor-ensembldb >=2.6.8,<2.9.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.21.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.37.0'
    - 'bioconductor-genomicranges >=1.32.0,<1.37.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.23.0'
    - 'bioconductor-summarizedexperiment >=1.12.0'
    - 'bioconductor-tximport >=1.10.0,<1.13.0'
    - r-base
    - r-jsonlite
    - r-rappdirs
    - r-tibble
  run:
    - 'bioconductor-annotationdbi >=1.44.0,<1.47.0'
    - 'bioconductor-biocfilecache >=1.6.0,<1.9.0'
    - 'bioconductor-biostrings >=2.50.0,<2.53.0'
    - 'bioconductor-ensembldb >=2.6.8,<2.9.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.21.0'
    - 'bioconductor-genomicfeatures >=1.34.0,<1.37.0'
    - 'bioconductor-genomicranges >=1.32.0,<1.37.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.23.0'
    - 'bioconductor-summarizedexperiment >=1.12.0'
    - 'bioconductor-tximport >=1.10.0,<1.13.0'
    - r-base
    - r-jsonlite
    - r-rappdirs
    - r-tibble
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: GPL-2
  summary: 'Transcript quantification import from Salmon with automatic population of metadata and transcript ranges. Filtered, combined, or de novo transcriptomes can be linked to the appropriate sources with linkedTxomes and shared for reproducible analyses.'
extra:
  parent_recipe:
    name: bioconductor-tximeta
    path: recipes/bioconductor-tximeta
    version: 1.0.1

