{% set version = "15.0" %}

package:
  name: ibm-at{{ version }}-runtime
  version: {{ version }}

requirements:
  build: []
  run: []

build:
  skip: True  # [not ppc64le]
  number: 1
  track_feature:
    - opt

about:
  summary: "Package that checks for the presence of the IBM AT {{ version }} runtime"
