{% set name = "AnnotationDbi" %}
{% set version = "1.44.0" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "https://bioconductor.org/packages/{{ bioc_version }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: 'adf4a36fe832569c414e0b0d6ec69bd20f07b0d61be17b734ccb973e6bdca4a4'

requirements:
  build:
    - r-base {{ r_base }}
    - r-dbi
    - r-rsqlite
    - bioconductor-biocgenerics >=0.23.1
    - bioconductor-biobase >=1.17.0
    - bioconductor-iranges
  run:
    - r-base
    - r-dbi
    - r-rsqlite
    - bioconductor-biocgenerics >=0.23.1
    - bioconductor-biobase >=1.17.0
    - bioconductor-iranges

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/AnnotationDbi.html"
  license: Artistic 2.0
  summary: BioConductor Annotation Database Interface
  description: |
    Provides user interface and database connection code for annotation data
    packages using SQLite data storage.
