{% set name = 'prettyunits' %}
{% set version = '1.0.2' %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
  sha256: 35a4980586c20650538ae1e4fed4d80fdde3f212b98546fc3c7d9469a1207f5c

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - r-magrittr
    - r-assertthat

  run:
    - r-base
    - r-magrittr
    - r-assertthat

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://github.com/hadley/blob
  license: GPLv3
  summary: A simple s3 class for representing vectors of binary data ('blobs')


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: blob
# Title: A Simple S3 Class for Representing Vectors of Binary Data ('BLOBS')
# Version: 1.1.0
# Authors@R: c( person("Hadley", "Wickham", role = c("aut")), person("Kirill", "Muller", , "krlmlr+r@mailbox.org", role = c("cre")), person("RStudio", role = "cph") )
# Description: R's raw vector is useful for storing a single binary object. What if you want to put a vector of them in a data frame? The blob package provides the blob object, a list of raw vectors, suitable for use as a column in data frame.
# Imports: tibble
# License: GPL-3
# Encoding: UTF-8
# LazyData: true
# URL: https://github.com/hadley/blob
# BugReports: https://github.com/hadley/blob/issues
# Suggests: testthat, covr
# RoxygenNote: 6.0.1
# NeedsCompilation: no
# Packaged: 2017-06-17 04:01:59 UTC; muelleki
# Author: Hadley Wickham [aut], Kirill Muller [cre], RStudio [cph]
# Maintainer: Kirill Muller <krlmlr+r@mailbox.org>
# Repository: CRAN
# Date/Publication: 2017-06-17 14:57:46 UTC
#----------------------------------------------------------------------
