package:
  name: spades
  version: "3.9.0"

requirements:
  build:
    - cmake
    - python
    - bzip2
    - zlib
  run:
    - bwa
    - python
    - zlib

source:
  fn: "spades-3.9.0.tar.bz2"
  url:
    - "http://spades.bioinf.spbau.ru/release3.9.0/SPAdes-3.9.0.tar.gz"
  md5: "e0b589b5e3356a398c38ddf6421746a2"
  patches:
    - use-system-bwa.patch
    - ppc64le-folly.patch
    - power9_at12.patch

build:
  number: 0

test:
  commands:
    - spades.py --test

about:
  home: "http://bioinf.spbau.ru/en/spades"
  license: GPLv2
  license_file: LICENSE
  summary: "Genome assembler intended for both standard isolates and single-cell MDA bacteria assemblies"
