package:
  name: perl-devel-stacktrace
  version: "2.04"

source:
  url: https://cpan.metacpan.org/authors/id/D/DR/DROLSKY/Devel-StackTrace-2.04.tar.gz
  sha256: cd3c03ed547d3d42c61fa5814c98296139392e7971c092e09a431f2c9f5d6855

build:
  number: 0
  noarch: True
  
requirements:
  host:
    - perl==5.26.2

  run:
    - perl==5.26.2

test:
  imports:
    - Devel::StackTrace
    - Devel::StackTrace::Frame

about:
  home: http://metacpan.org/release/Devel-StackTrace
  license: artistic_2
  summary: 'An object representing a stack trace'
