{% set name = "Biobase" %}
{% set version = "2.42.0" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "https://bioconductor.org/packages/{{ bioc_version }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: '36729cf3fa2cf42cc64c7f8f4afe5d0dfc64cc860baea721c2741739b335d982'

requirements:
  build:
    - r-base {{ r_base }}
    - bioconductor-biocgenerics >=0.3.2
  run:
    - r-base
    - bioconductor-biocgenerics >=0.3.2

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/Biobase.html"
  license: Artistic 2.0
  summary: Base functions for Bioconductor
  description: |
    Functions that are needed by many other Bioconductor packages or which
    replace standard R functions.
