{% set version = "1.0.4" %}

package:
  name: bam2fasta
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/b/bam2fasta/bam2fasta-{{ version }}.tar.gz
  sha256: 3afc9843b21ebd764f005825b93899016313d8645ecde9a04e52dddabc4015af

build:
  entry_points:
    - bam2fasta = bam2fasta.__main__:main
  number: 2
#  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build: 
  host:
    - python==3.7.6
    - pip
    - cython >=0.25.2
    - setuptools >=38.6.0
    - setuptools_scm
    - setuptools_scm_git_archive
    - numpy==1.18.1

  run:
    - python==3.7.6
    - pathos
    - pysam ==0.15.4
    - screed>=1.0
    - tqdm==4.36.1
    - numpy==1.18.1
    - pysam==0.15.4
    - libopenblas

test:
  imports:
    - bam2fasta

  commands:
    - bam2fasta --help
    - bam2fasta info


about:
  home: https://github.com/czbiohub/bam2fasta
  license: MIT License
  license_file: LICENSE
  summary: 'bam2fasta: cli tool to convert bam to fastas'
  license_family: MIT
  dev_url: https://github.com/czbiohub/bam2fasta

extra:
  recipe-maintainers:
    - pranathi7
  identifiers:
    - biotools:bam2fasta
