package:
  name: velvet
  version: "1.2.10"

# Use conda's gcc/libgcc on OSX to enable use of OpenMP
requirements:
  build:
    - zlib
    - gcc >=4.8.5     # [osx]
  run:
    - zlib
    - libgcc >=4.8.5  # [osx]

source:
  fn: velvet_1.2.10.tgz
  url:
    - "http://www.ebi.ac.uk/~zerbino/velvet/velvet_1.2.10.tgz"
  md5: 6e28c4b9bedc5f7ab2b947e7266a02f6
  patches:
    - velvet-makefile.patch

build:
  number: 2
  features:
  script_env:
    - MAKE_JOBS

test:
  source_files:
    - data
    - tests

about:
  home: http://www.ebi.ac.uk/~zerbino/velvet/
  license: GPLv2
  license_file: LICENSE.txt
  summary: "Sequence assembler for very short reads"
