{% set version = "1.0.4" %}

package:
  name: bam2fasta
  version: {{ version }}

source:
  fn: "bam2fasta-{{ version }}.tar.gz"
  url: https://github.com/czbiohub/bam2fasta/archive/v{{ version }}.tar.gz
  sha256: de2b1e1d00855fee951039f2cb5dc42593188c11098f1d5e74088d7641c81433

build:
  entry_points:
    - bam2fasta = bam2fasta.__main__:main
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed --no-cache-dir -vvv "

requirements:
  build:
  host:
    - python==3.7.6
    - pip
    - setuptools >=38.6.0
    - cython >=0.25.2
    - setuptools_scm
    - setuptools_scm_git_archive
    - numpy==1.17.5
  run:
    - python==3.7.6
    - pathos
    - pysam ==0.15.3
    - screed>=1.0
    - tqdm==4.36.1
    - pytest
    - codecov==2.0.15
    - numpy==1.17.5

test:
  imports:
    - bam2fasta

  commands:
    - bam2fasta --help
    - bam2fasta info

about:
  home: https://github.com/czbiohub/bam2fasta
  license: MIT License
  license_file: LICENSE
  summary: 'bam2fasta: cli tool to convert bam to fastas'
  license_family: MIT
  dev_url: https://github.com/czbiohub/bam2fasta

extra:
  recipe-maintainers:
    - pranathi7
  identifiers:
    - biotools:bam2fasta
