{% set version = "2.20.2" %}

package:
  name: picard
  version: "{{ version }}"

source:
  fn: "picard-{{ version }}.jar"
  url:
    - "https://github.com/broadinstitute/picard/releases/download/{{ version }}/picard.jar"
    - "http://download.lab7.io/sources/picard-{{ version }}.jar"
  md5: e3564e1affdbb525457258351a7364b2

build:
  number: 0

about:
  home: "http://broadinstitute.github.io/picard/"
  license: MIT
  summary: "Java tools for working with NGS data in the BAM format"
