package:
  name: biohpda
  version: 2020.03

build:
  number: 0

requirements:
  run:
    # BioHPDA is a software package that include a list of widely used genomic
    # and NGS applications available on Power system. It's part of IBM HPDA
    # solution. 
    - boost =={{ boost }}
    - python =={{ python }}
    - scipy ==1.3.2
    - r-base =={{ r_base }}
    - perl =={{ perl }}
    - numpy ==1.17.3
    # Tools available on Power platform. More tools will be added to the list.
    - bam2fasta ==1.0.2
    - bcftools ==1.9
    - bcl2fastq ==2.20.0.422
    - bioconductor-annotationdbi ==1.44.0
    - bioconductor-annotationfilter ==1.6.0
    - bioconductor-biobase ==2.42.0
    - bioconductor-biocfilecache ==1.8.0
    - bioconductor-biocgenerics ==0.28.0
    - bioconductor-biocparallel ==1.16.6
    - bioconductor-biomart ==2.38.0
    - bioconductor-biostrings ==2.50.2
    - bioconductor-delayedarray ==0.8.0
    - bioconductor-dupradar ==1.14.0
    - bioconductor-ebseq ==1.22.1
    - bioconductor-edger ==3.26.5
    - bioconductor-ensembldb ==2.6.8
    - bioconductor-genomeinfodb ==1.18.2
    - bioconductor-genomeinfodbdata ==1.2.0
    - bioconductor-genomicalignments ==1.18.1
    - bioconductor-genomicfeatures ==1.34.8
    - bioconductor-genomicranges ==1.34.0
    - bioconductor-iranges ==2.16.0
    - bioconductor-limma ==3.40.0
    - bioconductor-noiseq ==2.26.1
    - bioconductor-protgenerics ==1.14.0
    - bioconductor-rsamtools ==1.34.1
    - bioconductor-rsubread ==1.34.0
    - bioconductor-rtracklayer ==1.42.2
    - bioconductor-s4vectors ==0.20.1
    - bioconductor-shortread ==1.40.0
    - bioconductor-summarizedexperiment ==1.14.1
    - bioconductor-tximeta ==1.2.2
    - bioconductor-tximport ==1.12.3
    - bioconductor-xvector ==0.22.0
    - bioconductor-zlibbioc ==1.28.0
    - bowtie ==1.2.2
    - bowtie2 ==2.3.5.1
    - bwa ==0.7.17
    - bx-python ==0.8.4
    - cloog ==0.18.0
    - curl ==7.65.3
    - cmake ==3.14.0
    - colormath ==3.0.0
    - cutadapt ==2.4
    - deeptools ==3.3.1
    - deeptoolsintervals ==0.1.8
    - dnaio ==0.3
    - fastp ==0.20.0
    - fastqc ==0.11.8
    - gatk ==4.1.2.0
    - gatk-spark ==4.1.2.0
    - gffread ==0.11.4
    - gmap ==2019.09.12
    - gsl ==2.5
    - hdf5 ==1.8.16
    - hisat2 ==2.1.0
    - htseq ==0.11.2
    - htslib ==1.9.0
    - isl ==0.12.2
    - jemalloc ==5.1.0
    - kallisto ==0.46.0
    - khmer ==3.0.0a3
    - khtools ==0.1.0
    - mapper-test-data ==1.0
    - minimap2 ==2.17
    - multiqc ==1.7
    - openblas ==0.3.6
    - pathos ==0.2.5
    - pear ==0.9.6
    - picard ==2.21.2
    - plink ==1.90p
    - plink2 ==2.00a2
    - ppft ==1.6.6.1
    - preseq ==2.0.3
    - psutil ==5.6.3
    - py2bit ==0.3.0
    - pybigwig ==0.3.16
    - pysam ==0.15.3
    - qualimap ==2.2.2c
    - r-assertthat ==0.2.0
    - r-backports ==1.1.1
    - r-bh ==1.65.0_1
    - r-bindr ==0.1
    - r-bindrcpp ==0.2
    - r-bit ==1.1_12
    - r-bit64 ==0.9_7
    - r-bitops ==1.0_6
    - r-blob ==1.2.0
    - r-blockmodeling ==0.1.9
    - r-catools ==1.17.1
    - r-chron ==2.3_47
    - r-codetools ==0.2_15
    - r-crayon ==1.3.4
    - r-curl ==3.0
    - r-data.table ==1.12.4
    - r-dbi ==1.0.0
    - r-dbplyr ==1.1.0
    - r-digest ==0.6.12
    - r-dplyr ==0.7.4
    - r-ellipsis ==0.2.0.1
    - r-formatr ==1.5
    - r-futile.logger ==1.4.3
    - r-futile.options ==1.0.0
    - r-gdata ==2.18.0
    - r-getopt ==1.20.2
    - r-glue ==1.2.0
    - r-gplots ==3.0.1.1
    - r-gtools ==3.5.0
    - r-hms ==0.3
    - r-httr ==1.3.1
    - r-hwriter ==1.3.2
    - r-jsonlite ==1.5
    - r-kernsmooth ==2.23_15
    - r-lambda.r ==1.2.4
    - r-lattice ==0.20_35
    - r-latticeextra ==0.6_28
    - r-lazyeval ==0.2.1
    - r-locfit ==1.5_9
    - r-magrittr ==1.5
    - r-markdown ==1.1
    - r-matrix ==1.2_11
    - r-matrixstats ==0.52.2
    - r-memoise ==1.1.0
    - r-mime ==0.5
    - r-openssl ==0.9.9
    - r-optparse ==1.6.0
    - r-pkgconfig ==2.0.1
    - r-plogr ==0.2.0
    - r-praise ==1.0.0
    - r-prettyunits ==1.0.2
    - r-progress ==1.2.2
    - r-purrr ==0.2.4
    - r-r6 ==2.2.0
    - r-rappdirs ==0.3.1
    - r-rcolorbrewer ==1.1_2
    - r-rcpp ==0.12.17
    - r-rcurl ==1.95_4.11
    - r-rlang ==0.4.0
    - r-rsqlite ==2.1.1
    - r-snow ==0.4_2
    - r-stringi ==1.1.6
    - r-stringr ==1.2.0
    - r-testthat ==1.0.2
    - r-tibble ==1.3.4
    - r-vctrs ==0.2.0
    - r-xml ==3.98_1.11
    - r-xml2 ==1.1.1
    - r-zeallot ==0.1.0
    - rsem ==1.3.2
    - rseqc ==3.0.1
    - salmon ==0.14.2
    - samtools ==1.9.0
    - screed ==1.0.1
    - seqtk ==1.3
    - ska ==1.0
    - sortmerna ==2.1b
    - sourmash ==2.2.0
    - spades ==3.14.0
    - spectra ==0.0.11
    - star ==2.6.1d
    - stringtie ==2.0.4
    - subread ==1.6.4
    - trim-galore ==0.6.4
    - trimmomatic ==0.36
    - veclib-headers ==1.0.4
    - velvet ==1.2.10
    - xopen ==0.7.3
    - zlib ==1.2.11
about:
  summary: "Meta-packages for BioHPDA releases 2020.03 for IBM HPC Genomics"
