{% set name = "XVector" %}
{% set version = "0.22.0" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://bioconductor.org/packages/3.8/bioc/src/contrib/XVector_0.22.0.tar.gz"
  sha256: "b571cefe52955ec0f142dcf3b3f114983e21fad5a470560bcde099d67c80d705"

requirements:
  build:
    - r-base {{ r_base }}
    - bioconductor-biocgenerics >=0.19.2
    - bioconductor-s4vectors >=0.15.14
    - bioconductor-iranges >=2.9.18
    - bioconductor-zlibbioc
  run:
    - r-base
    - bioconductor-biocgenerics >=0.19.2
    - bioconductor-s4vectors >=0.15.14
    - bioconductor-iranges >=2.9.18
    - bioconductor-zlibbioc

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: Representation and manipulation of external sequences
  description: |
    Memory efficient S4 classes for storing sequences externally (behind an R
    external pointer or on disk).
