{% set version="99.2" %}

package:
    name: ensembl-vep
    version: '99.2'
source:
    sha256: 4488a5efe1047d489f1d1391d9e164cc159d0e9912e593b88140da279d0875cb
    url: https://github.com/Ensembl/ensembl-vep/archive/release/{{ version }}.tar.gz
build:
    noarch: generic
    number: '0'
    string: pl5262_0
requirements:
    host:
        - curl
        - perl 5.26.2
        - perl-archive-zip
        - perl-lwp-simple
        - perl-dbi
        - unzip
        - zlib 1.2.11
    run:
        - htslib 1.9
        - perl >=5.26.2,<5.26.3.0a0
        - perl-bio-db-hts >=2.11
        - perl-bioperl >=1.7.2
        - perl-dbd-mysql
        - perl-dbi
        - perl-io-compress
        - perl-json
        - perl-perlio-gzip
        - perl-sereal
        - perl-set-intervaltree
        - perl-text-csv
        - unzip
test:
    commands:
        - vep --help
        - vep_convert_cache --help
        - vep_install --help
        - haplo --help
        - variant_recoder --help
about:
    description: The VEP determines the effect of your variants (SNPs, insertions,
        deletions, CNVs or structural variants) on genes, transcripts, and protein
        sequence, as well as regulatory regions.
    home: http://www.ensembl.org/info/docs/tools/vep/index.html
    license: Apache 2.0
    summary: Ensembl Variant Effect Predictor
extra:
    copy_test_source_files: true
    final: true
    notes: "This package installs only the variant effect predictor (VEP) library\n\
        code. To install data libraries, you can use the 'vep_install' command\ninstalled\
        \ along with it. For example, to install the VEP library for human\nGRCh38\
        \ to a directory\n\nvep_install -a cf -s homo_sapiens -y GRCh38 -c /output/path/to/GRCh38/vep\
        \ --CONVERT\n\n(note that vep_install is renamed from INSTALL.pl\n to avoid\
        \ having generic script names in the PATH)\n\nThe --CONVERT flag is not required\
        \ but improves lookup speeds during\nruns. See the VEP documentation for more\
        \ details\n\nhttp://www.ensembl.org/info/docs/tools/vep/script/vep_cache.html\n"
