package:
  name: bioconductor-s4vectors
  version: "0.20.1"

source:
  fn: S4Vectors_0.20.1.tar.gz
  url: "http://bioconductor.org/packages/3.8/bioc/src/contrib/S4Vectors_0.20.1.tar.gz"
  md5: 688d781fb673cfb94e9f1c164be1e24e

requirements:
  build:
    - r-base=3.6.1
    - gcc  # [not ppc64le]
    - bioconductor-biocgenerics >=0.15.10
  run:
    - r-base=3.6.1
    - libgcc  # [not ppc64le]
    - bioconductor-biocgenerics >=0.15.10

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('S4Vectors')"  # [not win]
    - "\"%R%\" -e \"library('S4Vectors')\""  # [win]

about:
  home: "https://www.bioconductor.org/packages/release/bioc/html/S4Vectors.html"
  license: Artistic 2.0
  summary: "S4 implementation of vectors and lists"
