package:
  name: r-data.table
  version: "1.12.2"

source:
  fn: data.table_1.12.2.tar.gz
  url:
    - http://cran.r-project.org/src/contrib/data.table_1.12.2.tar.gz
    - http://cran.r-project.org/src/contrib/Archive/data.table/data.table_1.12.2.tar.gz
  sha256: "db55c18f0d703a8bc1c806dd1f7551bb405cb867717f52ef9dd64405394d22f5"

build:
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base
    - r-chron
    - gcc     # [not win and not ppc64le]

  run:
    - r-base
    - r-chron
    - libgcc  # [not win and not ppc64le]

test:
  commands:
    - $R -e "library('data.table')" # [not win]
    - "\"%R%\" -e \"library('data.table')\"" # [win]

about:
  home: 'https://github.com/Rdatatable/data.table/wiki'
  license: GPLv2
  summary: 'Extension of data.frame that supports fast operations on large (multi-GB) data'


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:

# Package: data.table
# Version: 1.12.2
# Title: Extension of Data.frame
# Author: M Dowle, A Srinivasan, T Short, S Lianoglou with contributions from R Saporta, E Antonyan
# Maintainer: Matt Dowle <mattjdowle@gmail.com>
# Depends: R (>= 2.14.1)
# Imports: methods, chron
# Suggests: ggplot2 (>= 0.9.0), plyr, reshape, reshape2, testthat (>= 0.4), hexbin, fastmatch, nlme, xts, bit64, gdata, GenomicRanges, caret, knitr, curl, zoo, plm
# Description: Fast aggregation of large data (e.g. 100GB in RAM), fast ordered joins, fast add/modify/delete of columns by group using no copies at all, list columns and a fast file reader (fread). Offers a natural and flexible syntax, for faster development.
# License: GPL (>= 2)
# URL: https://github.com/Rdatatable/data.table/wiki
# BugReports: https://github.com/Rdatatable/data.table/issues
# MailingList: datatable-help@lists.r-forge.r-project.org
# VignetteBuilder: knitr
# ByteCompile: TRUE
# NeedsCompilation: yes
# Packaged: 2015-09-19 04:47:43.628 UTC; mdowle
# Repository: CRAN
# Date/Publication: 2015-09-19 22:13:43
#----------------------------------------------------------------------
