{% set version = '0.3.2' %}

package:
  name: vcfanno
  version: {{ version }}

source:
  url: file:///gpfs/gpfs_4mb/rchen/Power9/NGS-App/sources/biobuilds/vcfanno/0.3.2/vcfanno_linux-ppc64le.tar.gz # [linux and ppc64le]
  sha256: 591cc6316c3c4109dfc3ab62024fa56531cbc5813e055acac3e20ca84f5c896a # [linux and ppc64le]
  url: https://github.com/brentp/vcfanno/releases/download/v{{ version }}/vcfanno_osx # [osx]
  sha256: 990949bfd1010f077e27922374c9a9bcbc6b34a02ef9f6e3e20db88496e925ff # [osx]
  url: https://github.com/brentp/vcfanno/releases/download/v{{ version }}/vcfanno_linux64 # [linux and x86_64]
  sha256: a3e52b72d960edfc5754c4865f168b4ad228ceebbf87f15424792b3737f54f60 # [linux and x86_64]

build:
  number: 0

requirements:

test:
  commands:
    - vcfanno

extra:
  skip-lints:
    - should_be_noarch_generic  # uses per platform binaries
    - should_not_be_noarch_source  # uses binaries

about:
  home: https://github.com/brentp/vcfanno
  license: MIT
  summary: annotate a VCF with other VCFs/BEDs/tabixed files
