{% set name = "ellipsis" %}
{% set version = "0.2.0.1" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
  sha256: "0e6528c5e8016c3617cc1cfcdb5a4bfeb073e0bd5ea76b43e56b0c3208a0a943"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - r-rlang

  run:
    - r-base
    - r-rlang

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://github.com/mllg/backports
  license: GPLv2
  summary: Reimplementations of functions introduced since R 3.0.0
  description: |
    Implementations of functions which have been introduced in R since version
    3.0.0. The backports are conditionally exported which results in R
    resolving the function names to the version shipped with R (if available)
    and uses the implemented backports as fallback. This way package developers
    can make use of the new functions without worrying about the minimum
    required R version.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: backports
# Type: Package
# Title: Reimplementations of Functions Introduced Since R-3.0.0
# Version: 1.1.1
# Author: Michel Lang <michellang@gmail.com>
# Maintainer: Michel Lang <michellang@gmail.com>
# Description: Implementations of functions which have been introduced in R since version 3.0.0. The backports are conditionally exported which results in R resolving the function names to the version shipped with R (if available) and uses the implemented backports as fallback. This way package developers can make use of the new functions without worrying about the minimum required R version.
# URL: https://github.com/mllg/backports
# BugReports: https://github.com/mllg/backports/issues
# License: GPL-2
# NeedsCompilation: yes
# ByteCompile: yes
# Depends: R (>= 3.0.0)
# Imports: utils
# RoxygenNote: 6.0.1
# Packaged: 2017-09-25 20:20:29 UTC; michel
# Repository: CRAN
# Date/Publication: 2017-09-25 22:09:46 UTC
#----------------------------------------------------------------------
