{% set version = "1.12.3" %}
{% set name = "tximport" %}
{% set bioc = "3.9" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
    - 'https://bioarchive.galaxyproject.org/{{ name }}_{{ version }}.tar.gz'
    - 'https://depot.galaxyproject.org/software/bioconductor-{{ name }}/bioconductor-{{ name }}_{{ version }}_src_all.tar.gz'
  sha256: 'ee0765e931b40b9a728c8cb94e60a6eab5e3794a4896b5a6d5d0ed4d17e8161c'
build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  noarch: generic
# Suggests: knitr, rmarkdown, testthat, tximportData, TxDb.Hsapiens.UCSC.hg19.knownGene, readr (>= 0.2.2), limma, edgeR, DESeq2 (>= 1.11.6), rhdf5, jsonlite, matrixStats, Matrix
requirements:
  host:
    - r-base=3.6.1
  run:
    - r-base
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
  summary: 'Import and summarize transcript-level estimates for transcript and gene-level analysis'
extra:
  identifiers:
    - biotools:tximport
  parent_recipe:
    name: bioconductor-tximport
    path: recipes/bioconductor-tximport
    version: 1.12.3
  recipe-maintainers:
    - roryk
