{% set name = "HISAT2" %}
{% set version = "2.1.0" %}
{% set sha256 = "c9f095bf9a7a8a31dbd0f0069779b5b154d23f9f0332c6160381c7687c4bac2e" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

requirements:
  build:
    - biobuilds-build
    - veclib-headers            # [toolchain == 'ibm-at10.0']
  host: []
  run:
    - perl
    - python

source:
  fn: "{{ name|lower }}-{{ version }}.zip"
  url:
    - "file:///gpfs/gpfs_4mb/rchen/Power9/NGS-App/sources/biobuilds/hisat2/2.1.0/hisat2-{{ version }}-source.zip"
  sha256: "{{ sha256 }}"

build:
  number: 0
  features:
    - opt                       # [toolchain != 'default']

test:
  source_files:
    - example

about:
  home: "http://ccb.jhu.edu/software/hisat2/index.shtml"
  license: "GPL 3"
  license_file: "LICENSE"
  summary: "Graph-based alignment of NGS reads to a population of genomes"
