# This file created by conda-build 3.19.2
# meta.yaml template originally from:
# /home/conda/recipe_root, last modified Thu May 14 13:31:26 2020
# ------------------------------------------------

package:
    name: tectonic
    version: 0.1.12
source:
    fn: tectonic-0.1.12.tar.gz
    patches:
        - fix-format-macros.patch
    sha256: b5e11cc128f9694cf71b8f4fc9a099e464294b5b18ff3a6fdbb6e5f0cf14b572
    url: https://crates.io/api/v1/crates/tectonic/0.1.12/download
build:
    number: '1'
    string: hb7de875_1
requirements:
    build:
        #- pkg-config 0.29.2 h516909a_1006
        - rust 1.43.1
    host:
        - ca-certificates 2020.6.20 hecda079_0
        - cairo 1.16.0 
        - fontconfig 2.13.1
        - freetype 2.10.2
        - gettext 0.19.8.1
        - glib 2.65.0 
        - graphite2 1.3.13
        - harfbuzz 2.4.0
        - icu 64.2
        - libffi 3.2.1
        - libiconv 1.15
        - libuuid 2.32.1
        - libxcb 1.13
        - libxml2 2.9.10
        - ncurses 6.1
        - openssl 1.1.1g
        - pcre 8.44
        - pixman 0.38.0
        - pthread-stubs 0.4
        - python 3.7.6
        - readline 8.0
        - sqlite 3.32.3
        - tk 8.6.10
        - xorg-kbproto 1.0.7
        - xorg-libice 1.0.10
        - xorg-libsm 1.2.3
        - xorg-libx11 1.6.9
        - xorg-libxau 1.0.9
        - xorg-libxdmcp 1.1.3
        - xorg-libxext 1.3.4
        - xorg-libxrender 0.9.10
        - xorg-renderproto 0.11.1
        - xorg-xextproto 7.3.0
        - xorg-xproto 7.0.31
        - xz 5.2.5
        - zlib 1.2.11
    run:
        - fontconfig >=2.13.1,<3.0a0
        - fontconfig >=2.13.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - freetype >=2.9.1,<3.0a0
        - graphite2
        - harfbuzz >=2.4.0,<3.0a0
        - icu
        - libpng
        - openssl >=1.1.1g,<1.1.2a
        - zlib >=1.2.11,<1.3.0a0
test:
    commands:
        - conda inspect linkages -p $PREFIX $PKG_NAME
        - tectonic --help
about:
    dev_url: https://github.com/tectonic-typesetting/tectonic/
    doc_url: https://tectonic-typesetting.github.io/learn.html
    home: https://tectonic-typesetting.github.io/
    license: MIT
    license_family: MIT
    license_file: LICENSE
    summary: A modernized, complete, standalone TeX/LaTeX engine.
extra:
    copy_test_source_files: true
    final: true
    recipe-maintainers:
        - pkgw
