{% set name = "BiocGenerics" %}
{% set version = "0.28.0" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "https://bioconductor.org/packages/{{ bioc_version }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
  sha256: "68e5a2737f847dd49c6cbd60a77291fd48b39fd219effef0a5c7eaf360d67733"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}

  run:
    - r-base=3.6.1

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: "http://bioconductor.org/packages/release/bioc/html/BiocGenerics.html"
  license: Artistic 2.0
  summary: "S4 generic functions needed by many Bioconductor packages"
