package:
  name: perl-version-next
  version: "1.000"

source:
  url: https://cpan.metacpan.org/authors/id/D/DA/DAGOLDEN/Version-Next-1.000.tar.gz
  md5: 4bafa527ff40edef40822f1f9a80fe51

build:
  noarch: generic
  number: 2

requirements:
  host:
    - perl==5.26.2
    - perl-test-simple
    - perl-test-exception
    - perl-pathtools
    - perl-apache-test
    - perl-extutils-makemaker
    - perl-sub-exporter
    - perl-perl-version

  run:
    - perl==5.26.2
    - perl-apache-test
    - perl-sub-exporter
    - perl-perl-version

test:
  imports:
    - Version::Next

about:
  home: https://github.com/dagolden/Version-Next
  license: apache_2_0
  summary: 'increment module version numbers simply and correctly'
