{% set name = "purrr" %}
{% set version = "0.2.4" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "ed8d0f69d29b95c2289ae52be08a0e65f8171abb6d2587de7b57328bf3b2eb71"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

  run:
    - r-base
    - r-magrittr >=1.5
    - r-rlang >=0.1
    - r-tibble

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
  license: GPLv3
  summary: Functional programming tools
  description: |
    A complete and consistent functional programming toolkit for R.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: purrr
# Title: Functional Programming Tools
# Version: 0.2.4
# Authors@R: c( person("Lionel", "Henry", , "lionel@rstudio.com", c("aut", "cre")), person("Hadley", "Wickham", , "hadley@rstudio.com", "aut"), person("RStudio", role = c("cph", "fnd")) )
# Description: A complete and consistent functional programming toolkit for R.
# License: GPL-3 | file LICENSE
# URL: http://purrr.tidyverse.org, https://github.com/tidyverse/purrr
# BugReports: https://github.com/tidyverse/purrr/issues
# Depends: R (>= 3.1)
# Imports: magrittr (>= 1.5), rlang (>= 0.1), tibble
# Suggests: covr, dplyr (>= 0.4.3), knitr, rmarkdown, testthat
# VignetteBuilder: knitr
# LazyData: true
# RoxygenNote: 6.0.1
# NeedsCompilation: yes
# Packaged: 2017-10-18 13:06:58 UTC; hadley
# Author: Lionel Henry [aut, cre], Hadley Wickham [aut], RStudio [cph, fnd]
# Maintainer: Lionel Henry <lionel@rstudio.com>
# Repository: CRAN
# Date/Publication: 2017-10-18 20:19:51 UTC
#----------------------------------------------------------------------
