package:
  name: biohpc
  version: 2019.08

build:
  number: 0

requirements:
  run:
    # BioHPC is a software package that include a list of widely used genomic
    # and NGS applications available on Power system. It's part of IBM HPDA
    # solution. 
    - boost =={{ boost }}
    - python ==3.7.3
    - scipy ==1.3.0
    - r-base =={{ r_base }}
    - perl =={{ perl }}
    # Tools available on Power platform. More tools will be added to the list.
    - bcftools ==1.9
    - bioconductor-annotationdbi ==1.44.0
    - bioconductor-annotationfilter ==1.6.0
    - bioconductor-biobase ==2.42.0
    - bioconductor-biocfilecache ==1.6.0
    - bioconductor-biocgenerics ==0.28.0
    - bioconductor-biocparallel ==1.16.6
    - bioconductor-biomart ==2.38.0
    - bioconductor-biostrings ==2.50.2
    - bioconductor-delayedarray ==0.8.0
    - bioconductor-dupradar ==1.14.0
    - bioconductor-ebseq ==1.22.1
    - bioconductor-edger ==3.26.0
    - bioconductor-ensembldb ==2.6.8
    - bioconductor-genomeinfodb ==1.18.2
    - bioconductor-genomeinfodbdata ==1.2.0
    - bioconductor-genomicalignments ==1.18.1
    - bioconductor-genomicfeatures ==1.34.8
    - bioconductor-genomicranges ==1.34.0
    - bioconductor-iranges ==2.16.0
    - bioconductor-limma ==3.40.0
    - bioconductor-noiseq ==2.26.1
    - bioconductor-protgenerics ==1.14.0
    - bioconductor-rsamtools ==1.34.1
    - bioconductor-rsubread ==1.34.0
    - bioconductor-rtracklayer ==1.42.2
    - bioconductor-s4vectors ==0.20.1
    - bioconductor-shortread ==1.40.0
    - bioconductor-summarizedexperiment ==1.12.0
    - bioconductor-tximeta ==1.0.3
    - bioconductor-tximport ==1.10.1
    - bioconductor-xvector ==0.22.0
    - bioconductor-zlibbioc ==1.28.0
    - blas ==1.0
    - bowtie ==1.2.2
    - bowtie2 ==2.3.5.1
    - bwa ==0.7.17
    - curl ==7.65.2
    - deeptools ==3.2.1
    - deeptoolsintervals ==0.1.8
    - fastqc ==0.11.8
    - gatk ==4.1.2.0
    - gffread ==0.11.4
    - hisat2 ==2.1.0
    - htslib ==1.9.0
    - markdown ==3.1.1
    - markupsafe ==1.1.1
    - matplotlib ==3.0.3
    - multiqc ==1.7
    - ncurses ==6.1
    - openblas ==0.3.6
    - picard ==2.20.2
    - plotly ==4.0.0
    - preseq ==2.0.3
    - psutil ==5.6.3
    - py2bit ==0.3.0
    - pybigwig ==0.3.16
    - pysam ==0.15.3
    - qualimap ==2.2.2c
    - r-assertthat ==0.2.0
    - r-backports ==1.1.1
    - r-bh ==1.65.0_1
    - r-bindr ==0.1
    - r-bindrcpp ==0.2
    - r-bit ==1.1_12
    - r-bit64 ==0.9_7
    - r-bitops ==1.0_6
    - r-blob ==1.2.0
    - r-blockmodeling ==0.1.9
    - r-catools ==1.17.1
    - r-chron ==2.3_47
    - r-codetools ==0.2_15
    - r-crayon ==1.3.4
    - r-curl ==3.0
    - r-data.table ==1.12.2
    - r-dbi ==1.0.0
    - r-dbplyr ==1.1.0
    - r-digest ==0.6.12
    - r-dplyr ==0.7.4
    - r-ellipsis ==0.2.0.1
    - r-futile.logger ==1.4.3
    - r-futile.options ==1.0.0
    - r-gdata ==2.18.0
    - r-getopt ==1.20.2
    - r-glue ==1.2.0
    - r-gplots ==3.0.1.1
    - r-gtools ==3.5.0
    - r-hms ==0.3
    - r-httr ==1.3.1
    - r-hwriter ==1.3.2
    - r-jsonlite ==1.5
    - r-kernsmooth ==2.23_15
    - r-lambda.r ==1.2
    - r-lattice ==0.20_35
    - r-latticeextra ==0.6_28
    - r-lazyeval ==0.2.1
    - r-locfit ==1.5_9
    - r-magrittr ==1.5
    - r-markdown ==0.9
    - r-matrix ==1.2_11
    - r-matrixstats ==0.52.2
    - r-memoise ==1.1.0
    - r-mime ==0.5
    - r-openssl ==0.9.9
    - r-optparse ==1.6.0
    - r-pkgconfig ==2.0.1
    - r-plogr ==0.2.0
    - r-praise ==1.0.0
    - r-prettyunits ==1.0.2
    - r-progress ==1.2.2
    - r-purrr ==0.2.4
    - r-r6 ==2.2.0
    - r-rappdirs ==0.3.1
    - r-rcolorbrewer ==1.1_2
    - r-rcpp ==0.12.17
    - r-rcurl ==1.95_4.11
    - r-rlang ==0.4.0
    - r-rsqlite ==2.1.1
    - r-snow ==0.4_2
    - r-stringi ==1.1.6
    - r-stringr ==1.2.0
    - r-testthat ==1.0.2
    - r-tibble ==1.3.4
    - r-vctrs ==0.2.0
    - r-xml ==3.98_1.11
    - r-zeallot ==0.1.0
    - rsem ==1.3.2
    - rseqc ==3.0.0
    - salmon ==0.14.0
    - samtools ==1.9.0
    - star ==2.6.1d
    - stringtie ==1.3.6
    - subread ==1.6.4
    - trim-galore ==0.6.2
about:
  summary: "Meta-packages for BioHPC releases 2019.08"
