{% set version = "3.28.0" %}
{% set name = "edgeR" %}
{% set bioc = "3.10" %}
 
package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - "https://bioconductor.org/packages/3.10/bioc/src/contrib/Archive/edgeR/edgeR_3.28.0.tar.gz"
  sha256: 036ea5bf3b4fe2b6a0ea8f081e7d9071eb34d4ad132708763a2bcce89733f4d4
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: AnnotationDbi, jsonlite, org.Hs.eg.db, readr, rhdf5, splines
# SystemRequirements: C++11
requirements:
  host:
    - 'bioconductor-limma >=3.42.0,<3.43.0'
    - r-base=3.6.1
    - r-locfit
    - r-rcpp
  run:
    - 'bioconductor-limma >=3.42.0,<3.43.0'
    - r-base=3.6.1
    - r-locfit
    - r-rcpp
  build:
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Differential expression analysis of RNA-seq expression profiles with biological replication. Implements a range of statistical methodology based on the negative binomial distributions, including empirical Bayes estimation, exact tests, generalized linear models and quasi-likelihood tests. As well as RNA-seq, it be applied to differential signal analysis of other types of genomic data that produce counts, including ChIP-seq, Bisulfite-seq, SAGE and CAGE.'
  license_file: '{{ environ["PREFIX"] }}/lib/R/share/licenses/GPL-3'
extra:
  identifiers:
    - biotools:edger
  parent_recipe:
    name: bioconductor-edger
    path: recipes/bioconductor-edger
    version: 3.22.5

