package:
  name: cmake
  version: "3.14.0"

source:
  fn: "cmake-3.14.0.tar.gz"
  url:
    - "https://cmake.org/files/v3.14/cmake-3.14.0.tar.gz"
  sha1: "30e5423245d98ad98f6ee0c5f73c587846b99d6b"

requirements:
  build:
    - bzip2
#    - curl
    - expat
    - ncurses
    - xz
    - zlib
  run:
    - bzip2
#    - curl
    - expat
    - ncurses
    - xz
    - zlib

build:
  # Give our package a large build number so it's preferred over the
  # corresponding package (if any) in the "defaults" channel.
  number: 700

test:
  files:
    - test-https-download.cmake
  commands:
    - cmake --version
    - cmake -V -P test-https-download.cmake

about:
  home: "https://cmake.org/"
  license: BSD
  summary: "Open-source, cross-platform tools designed to build, test, and package software"
