package:
  name: deeptools
  version: '3.2.1'

source:
  url: https://files.pythonhosted.org/packages/cb/31/bfd1dd80e048075269d083230a635d1285ad2229cf22af14fb104e764cce/deepTools-3.2.1.tar.gz
  sha256: ccbabb46d6c17c927e96fadc43d8d4770efeaf40b9bcba3b94915a211007378e

build:
  number: 0
  noarch: python
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv"

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pybigwig >=0.2.3
    - numpy >=1.9.0
    - scipy >=0.17.0
    - matplotlib >=2.1.1
    - pysam >=0.14.0
    - py2bit >=0.2.0
    - plotly >=1.9.0
    - deeptoolsintervals >=0.1.8

test:
  imports:
    - deeptools

  commands:
    - bamCompare --version

about:
  home: https://github.com/deeptools/deepTools
  license: GPL3
  summary: A set of user-friendly tools for normalization and visualzation of deep-sequencing data

extra:
  identifiers:
    - biotools:deeptools
    - doi:10.1093/nar/gkw257
