{% set name = 'bit64' %}
{% set version = '0.9-7' %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "7b9aaa7f971198728c3629f9ba1a1b24d53db5c7e459498b0fdf86bbd3dff61f"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - r-bit >=1.1_12

  run:
    - r-base
    - r-bit >=1.1_12

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: http://ff.r-forge.r-project.org/
  license: GPLv2
  summary: A S3 class for vectors of 64bit integers


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: bit64
# Type: Package
# Title: A S3 Class for Vectors of 64bit Integers
# Version: 0.9-7
# Date: 2017-05-07
# Author: Jens OehlschlAgel <Jens.Oehlschlaegel@truecluster.com>
# Maintainer: Jens OehlschlAgel <Jens.Oehlschlaegel@truecluster.com>
# Depends: R (>= 3.0.1), bit (>= 1.1-12), utils, methods, stats
# Description:  Package 'bit64' provides serializable S3 atomic 64bit (signed) integers.  These are useful for handling database keys and exact counting in +-2^63. WARNING: do not use them as replacement for 32bit integers, integer64 are not supported for subscripting by R-core and they have different semantics when  combined with double, e.g. integer64 + double => integer64.  Class integer64 can be used in vectors, matrices, arrays and data.frames.  Methods are available for coercion from and to logicals, integers, doubles,  characters and factors as well as many elementwise and summary functions.  Many fast algorithmic operations such as 'match' and 'order' support inter- active data exploration and manipulation and optionally leverage caching.
# License: GPL-2
# LazyLoad: yes
# ByteCompile: yes
# URL: http://ff.r-forge.r-project.org/
# Encoding: UTF-8
# NeedsCompilation: yes
# Packaged: 2017-05-07 19:07:42 UTC; jo
# Repository: CRAN
# Date/Publication: 2017-05-08 13:21:40 UTC
#----------------------------------------------------------------------
