{% set version = "2.0.4" %}

package:
  name: stringtie
  version: {{ version }}

build:
  number: 0

requirements:
  build:
  host:
    # curl is used to download prepDE.py
  run:
    - python

source:
  sha256: "19853ff812cb804cecdb8974470ef6c8974addd777ad31f3c5d93c5f4d2d3048"
  url: http://ccb.jhu.edu/software/stringtie/dl/stringtie-2.0.4.tar.gz

test:
  commands:
    - "stringtie 2>&1 | grep Assemble"
    - prepDE.py --help

about:
  home: https://ccb.jhu.edu/software/stringtie/
  license: Artistic License 2.0
  summary: Transcriptome assembly and quantification for RNA-seq

extra:
  identifiers:
    - biotools:StringTie
    - doi:10.1038/nbt.3122
