package:
    name: perl-libwww-perl
    version: '6.15'
source:
    fn: libwww-perl-6.15.tar.gz
    md5: 6888c9d8728cd6f3ea3c9754461c9f94
    url: https://cpan.metacpan.org/authors/id/E/ET/ETHER/libwww-perl-6.15.tar.gz
build:
    number: '0'
requirements:
    build:
        - perl==5.26.2
        - perl-threaded
        - perl-ntlm
        - perl-encode-locale
        - perl-file-listing
        - perl-html-parser
        - perl-http-cookies
        - perl-http-daemon
        - perl-http-date
        - perl-http-message
        - perl-http-negotiate
        - perl-lwp-mediatypes
        - perl-net-http
        - perl-uri
        - perl-www-robotrules
    run:
        - perl==5.26.2
        - perl-threaded
        - perl-ntlm
        - perl-encode-locale
        - perl-file-listing
        - perl-html-parser
        - perl-http-cookies
        - perl-http-daemon
        - perl-http-date
        - perl-http-message
        - perl-http-negotiate
        - perl-lwp-mediatypes
        - perl-net-http
        - perl-uri
        - perl-www-robotrules
test:
    imports:
        - LWP
        - LWP::Authen::Basic
        - LWP::Authen::Digest
        - LWP::Authen::Ntlm
        - LWP::ConnCache
        - LWP::Debug
        - LWP::DebugFile
        - LWP::MemberMixin
        - LWP::Protocol
        - LWP::Protocol::cpan
        - LWP::Protocol::data
        - LWP::Protocol::file
        - LWP::Protocol::ftp
        - LWP::Protocol::gopher
        - LWP::Protocol::http
        - LWP::Protocol::loopback
        - LWP::Protocol::nntp
        - LWP::Protocol::nogo
        - LWP::RobotUA
        - LWP::Simple
        - LWP::UserAgent
about:
    home: http://metacpan.org/pod/libwww-perl
    license: perl_5
    summary: The World-Wide Web library for Perl
