 {% set version = "4.0.2" %}

package:
  name: cancerit-allelecount
  version: {{ version }}
source:
  url: https://github.com/cancerit/alleleCount/archive/v{{ version }}.tar.gz
  sha256: f11be42c3adde1796c98bb5b1443f43d60e0c62c66daadfa965c87d391d33449
build:
  number: 2
  skip: True # [osx]
  string: hpda0720_2
requirements:
  build:
    - htslib=1.10.2
  host:
    - zlib
    - wget
    - curl
    - bzip2
    - xz
    - libdeflate
    - htslib=1.10.2
  run:
    - zlib
    - htslib=1.10.2
test:
  commands:
    - 'alleleCounter -h'
about:
  home: https://github.com/cancerit/alleleCount
  license: GPLv3
  summary: Support code for NGS copy number algorithms
