{% set version = '0.20-35' %}

package:
  name: r-lattice
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-lattice_{{ version }}.tar.gz"
  url:
    - "https://cran.r-project.org/src/contrib/lattice_{{ version }}.tar.gz"
    - "https://cran.r-project.org/src/contrib/Archive/lattice/lattice_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-lattice_{{ version }}.tar.gz"
  sha256: "0829ab0f4dec55aac6a73bc3411af68441ddb1b5b078d680a7c2643abeaa965d"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('lattice')"

about:
  home: "http://lattice.r-forge.r-project.org/"
  license: GPL
  summary: "High-level data visualization system inspired by Trellis graphics"
  description: |
    A powerful and elegant high-level data visualization system inspired by
    Trellis graphics, with an emphasis on multivariate data. Lattice is
    sufficient for typical graphics needs, and is also flexible enough to
    handle most nonstandard requirements. See ?Lattice for an introduction.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:

# Package: lattice
# Version: 0.20-35
# Date: 2017-03-23
# Priority: recommended
# Title: Trellis Graphics for R
# Author: Deepayan Sarkar <deepayan.sarkar@r-project.org>
# Maintainer: Deepayan Sarkar <deepayan.sarkar@r-project.org>
# Description: A powerful and elegant high-level data visualization system inspired by Trellis graphics, with an emphasis on multivariate data. Lattice is sufficient for typical graphics needs, and is also flexible enough to handle most nonstandard requirements. See ?Lattice for an introduction.
# Depends: R (>= 3.0.0)
# Suggests: KernSmooth, MASS, latticeExtra
# Imports: grid, grDevices, graphics, stats, utils
# Enhances: chron
# LazyLoad: yes
# LazyData: yes
# License: GPL (>= 2)
# URL: http://lattice.r-forge.r-project.org/
# BugReports: https://github.com/deepayan/lattice/issues
# NeedsCompilation: yes
# Packaged: 2017-03-25 11:25:40 UTC; deepayan
# Repository: CRAN
# Date/Publication: 2017-03-25 18:05:47 UTC
#----------------------------------------------------------------------
