{% set name = "Biostrings" %}
{% set version = "2.50.2" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://bioconductor.org/packages/3.8/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
  sha256: c7a1d70eb87915b2eac7490b4ac1f2e01dac3bc6ee470a3e93603d1311c39899

requirements:
  build:
    - r-base {{ r_base }}
    - bioconductor-biocgenerics >=0.15.6
    - bioconductor-s4vectors >=0.13.13
    - bioconductor-iranges >=2.9.18
    - bioconductor-xvector >=0.11.6
  run:
    - r-base
    - bioconductor-biocgenerics >=0.15.6
    - bioconductor-s4vectors >=0.13.13
    - bioconductor-iranges >=2.9.18
    - bioconductor-xvector >=0.11.6

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

test:
  commands:
    - $R -e "library('Biostrings')"            # [not win]
    - "\"%R%\" -e \"library('Biostrings')\""   # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/Biostrings.html"
  license: "Artistic 2.0"
  summary: "Efficient manipulation of biological strings"
  description: |
    Memory efficient string containers, string matching algorithms, and other
    utilities, for fast manipulation of large biological sequences or sets of
    sequences.
