{% set version = "3.2.2" %}

package:
  name: sourmash
  version: {{ version }}

source:
  url: https://files.pythonhosted.org/packages/4a/8e/90b05079259d76d98b40a6947265c322bb9c2d3031805eb5d48204182655/sourmash-3.2.2.tar.gz
  sha256: ae8b6fcb17a57d95c29511cc3a091783c48fe52da9a89c461cdd93c7e730a147

build:
  entry_points:
    - sourmash = sourmash.__main__:main
  number: 1
#  script: "{{ PYTHON }} -m pip install --no-deps --ignore-installed -vv ."
  script: "{{ PYTHON }} -m pip install --ignore-installed -vv ."

requirements:
  build:
  host:
    - python
    - pip
    - setuptools >=38.6.0
    - cython >=0.25.2
    - milksnake
    - cffi
    - setuptools_scm
    - setuptools_scm_git_archive

  run:
    - python
    - screed >=1.0
    - ijson <2.5
    - numpy 
    - matplotlib
    - scipy
    - cffi
    - deprecation
    - khmer >=2.1
    - yajl

test:
  imports:
    - sourmash

  commands:
    - sourmash --help
    - sourmash info

about:
  home: https://github.com/dib-lab/sourmash
  summary: 'Compute and compare MinHash signatures for DNA data sets.'
  license: BSD License
  license_family: BSD
  license_file: LICENSE
  dev_url: https://github.com/dib-lab/sourmash

extra:
  identifiers:
    - biotools:sourmash
    - doi:10.21105/joss.00027
    - doi:10.12688/f1000research.19675.1
  recipe-maintainers:
    - luizirber
  authors:
    - luizirber
    - ctb
