package:
  name: "plink2"
  version: "2.00a2"

build:
  number: 1

source:
  url: file:///gpfs/gpfs_4mb/rchen/Power9/NGS-App/sources/biobuilds/plink/plink-2.0.tar.gz
  sha256: f72d60b5f8d93bac72e2cd0ec7047c44eab8665d6a5401cb601dfb38f5a506bd
# Official version list below:
#  url: http://www.cog-genomics.org/static/bin/plink2_src_191128.zip
#  sha256: 7b998277a2be036da30e70d0fd55174044334f00a73b8f3335633478b384f570

requirements:
  build:
  host:
  run:

test:
  commands:
    - plink2 --help | grep "PLINK v2.00a2"

about:
  home: https://www.cog-genomics.org/plink/2.0/
  license: GPL
  license_file: LICENSE
  summary: Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.
