{% set name = "hwriter" %}
{% set version = "1.3.2" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
  sha256: "6b3531d2e7a239be9d6e3a1aa3256b2745eb68aa0bdffd2076d36552d0d7322b"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/


requirements:
  build:
    - r-base {{ r_base }}

  run:
    - r-base

test:
  commands:
    - $R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://CRAN.R-project.org/package=hwriter
  license: LGPLv2.1
  summary: "Easy-to-use and versatile functions to output R objects in HTML format"
  license: LGPL-2.1


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: hwriter
# Title: HTML Writer - Outputs R objects in HTML format
# Version: 1.3.2
# Author: Gregoire Pau <gregoire.pau@gmail.com>
# Depends: R (>= 2.6.0)
# Description: Easy-to-use and versatile functions to output R objects in HTML format
# Maintainer: Gregoire Pau <gregoire.pau@gmail.com>
# License: LGPL-2.1
# Packaged: 2014-09-08 20:22:43 UTC; paug
# Repository: CRAN
# Date/Publication: 2014-09-10 09:07:38
# NeedsCompilation: no
#----------------------------------------------------------------------
