{% set version = "3.22.5" %}
{% set name = "edgeR" %}
{% set bioc = "3.7" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - "https://bioconductor.org/packages/3.7/bioc/src/contrib/edgeR_3.22.5.tar.gz"
  sha256: 47d2234f29a4717e4f7079f23ef300d910e81adf4721d58d62aaf18ae06c6c5e
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: AnnotationDbi, jsonlite, org.Hs.eg.db, readr, rhdf5, splines
# SystemRequirements: C++11
requirements:
  host:
    - 'bioconductor-limma >=3.40.0,<3.41.0'
    - r-base=3.6.1
    - r-locfit
    - r-rcpp
  run:
    - 'bioconductor-limma >=3.40.0,<3.41.0'
    - r-base=3.6.1
    - r-locfit
    - r-rcpp
  build:
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'GPL (>=2)'
  summary: 'Differential expression analysis of RNA-seq expression profiles with biological replication. Implements a range of statistical methodology based on the negative binomial distributions, including empirical Bayes estimation, exact tests, generalized linear models and quasi-likelihood tests. As well as RNA-seq, it be applied to differential signal analysis of other types of genomic data that produce counts, including ChIP-seq, Bisulfite-seq, SAGE and CAGE.'
extra:
  identifiers:
    - biotools:edger
  parent_recipe:
    name: bioconductor-edger
    path: recipes/bioconductor-edger
    version: 3.22.5

