# Primary compiler for building this package is IBM Advance Toolchain version 12,
# unless otherwise specified.

boost:
  - "1.67.0"
perl:
  - "5.26.2"
python:
  - "3.7.6"
r_base:
  - "3.6.1"
numpy:
  - "1.18.1"
