{% set version = "15.0" %}

package:
  name: "ibm-at{{ version }}-build"
  version: "{{ version }}"

requirements:
  build: []
  run: []

build:
  skip: True    # [not linux or not ppc64le]
  number: 4
  track_feature:
    - opt

about:
  home: "https://www.biobuilds.org/"
  license: BSD
  summary: "Support scripts for building packages using IBM Advance Toolchain {{ version }}"
