{% set version = "1.3.6" %}

package:
  name: stringtie
  version: {{ version }}

build:
  number: 0

requirements:
  build:
  host:
    # curl is used to download prepDE.py
  run:
    - python

source:
  sha256: 41062d58799e3390c7502dfd6c82a3a976081aa3f0ea400b22f9fd73a43f7801
  url: file:///gpfs/gpfs_4mb/rchen/Power9/NGS-App/sources/biobuilds/stringtie/1.3.6/stringtie-{{ version }}.tar.gz

test:
  commands:
    - "stringtie 2>&1 | grep Assemble"
    - prepDE.py --help

about:
  home: https://ccb.jhu.edu/software/stringtie/
  license: Artistic License 2.0
  summary: Transcriptome assembly and quantification for RNA-seq

extra:
  identifiers:
    - biotools:StringTie
    - doi:10.1038/nbt.3122
