# This file created by conda-build 3.17.8
# meta.yaml template originally from:
# /opt/recipe, last modified Fri Jun  7 09:18:11 2019
# ------------------------------------------------

package:
    name: cnvkit
    version: 0.9.6
source:
    sha256: c6f20e7cf22b20c81325f7cd55d4a8c835b37b1227f274386a6cc48450be9acd
    url: https://github.com/etal/cnvkit/archive/v0.9.6.tar.gz
build:
    number: '1'
    string: py37_1
requirements:
    host:
        - bzip2 1.0.6 h14c3975_1002
        - ca-certificates 2019.3.9 hecc5488_0
        - certifi 2019.3.9 py37_0
        - libffi 3.2.1 he1b5a44_1006
        - libgcc-ng 8.2.0 hdf63c60_1
        - libstdcxx-ng 8.2.0 hdf63c60_1
        - ncurses 6.1 hf484d3e_1002
        - openssl 1.1.1b h14c3975_1
        - pip 19.1.1 py37_0
        - python 3.7.3 h5b0a415_0
        - readline 7.0 hf8c457e_1001
        - setuptools 41.0.1 py37_0
        - sqlite 3.28.0 h8b20d00_0
        - tk 8.6.9 hed695b0_1002
        - wheel 0.33.4 py37_0
        - xz 5.2.4 h14c3975_1001
        - zlib 1.2.11 h14c3975_1004
    run:
        - bioconductor-dnacopy
        - biopython >=1.62
        - future >=0.15.2
        - matplotlib >=1.3.1
        - numpy >=1.9
        - pandas >=0.22.0
        - pomegranate >=0.9.0
        - pyfaidx >=0.4.7
        - pysam >=0.10.0
        - python >=3.7,<3.8.0a0
        - python-dateutil >=2.5.0
        - r-base >=3.4.1
        - r-cghflasso
        - reportlab >=3.0
        - scipy >=0.15.0
test:
    commands:
        - cnvkit.py -h
    imports:
        - cnvlib
        - skgenome
about:
    home: https://github.com/etal/cnvkit
    license: Apache License 2.0
    summary: Copy number variant detection from high-throughput sequencing
extra:
    copy_test_source_files: true
    final: true
    identifiers:
        - biotools:cnvkit
        - doi:10.1371/journal.pcbi.1004873
