package:
    name: perl-extutils-makemaker
    version: '7.36'
source:
    sha256: 06cef6429315cdc6afa9b2dc6fbdfa33538b6f68c827f441294621858e28c558
    url: https://cpan.metacpan.org/authors/id/B/BI/BINGOS/ExtUtils-MakeMaker-7.36.tar.gz
build:
    number: '1'
    noarch: generic
requirements:
    host:
        - perl==5.26.2
    run:
        - perl==5.26.2
test:
    imports:
        - ExtUtils::Command
        - ExtUtils::Command::MM
        - ExtUtils::Liblist
        - ExtUtils::Liblist::Kid
        - ExtUtils::MM
        - ExtUtils::MM_AIX
        - ExtUtils::MM_Any
        - ExtUtils::MM_BeOS
        - ExtUtils::MM_Cygwin
        - ExtUtils::MM_DOS
        - ExtUtils::MM_Darwin
        - ExtUtils::MM_MacOS
        - ExtUtils::MM_NW5
        - ExtUtils::MM_OS2
        - ExtUtils::MM_QNX
        - ExtUtils::MM_UWIN
        - ExtUtils::MM_Unix
        - ExtUtils::MM_VMS
        - ExtUtils::MM_VOS
        - ExtUtils::MM_Win32
        - ExtUtils::MM_Win95
        - ExtUtils::MY
        - ExtUtils::MakeMaker
        - ExtUtils::MakeMaker::Config
        - ExtUtils::MakeMaker::Locale
        - ExtUtils::MakeMaker::version
        - ExtUtils::MakeMaker::version::regex
        - ExtUtils::MakeMaker::version::vpp
        - ExtUtils::Mkbootstrap
        - ExtUtils::Mksymlists
        - ExtUtils::testlib
about:
    home: https://metacpan.org/release/ExtUtils-MakeMaker
    license: perl_5
    summary: Create a module Makefile
extra:
    copy_test_source_files: true
    final: true
