{% set name = "SummarizedExperiment" %}
{% set version = "1.14.1" %}
{% set bioc_version = "3.9" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://bioconductor.org/packages/3.9/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
  sha256: '6edc47f11d6437038a91a457a8770e7bf47cf1d51848c2bec420dfd8f27f1c2e'

requirements:
  build:
    - r-base {{ r_base }}
    - r-matrix
    - bioconductor-genomicranges >=1.29.14
    - bioconductor-biobase
    - bioconductor-delayedarray >=0.3.20
  run:
    - r-base
    - r-matrix
    - bioconductor-genomicranges >=1.29.14
    - bioconductor-biobase
    - bioconductor-delayedarray >=0.3.20

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: SummarizedExperiment container
  description: |
    The SummarizedExperiment container contains one or more assays, each
    represented by a matrix-like object of numeric or other mode. The rows
    typically represent genomic ranges of interest and the columns represent
    samples.
