package:
  name: fastqc
  version: "0.11.8"

requirements:
  run:
    - perl    # needed for launcher script
    - picard

source:
  fn: fastqc_v0.11.8.zip
  url:
    - http://www.bioinformatics.babraham.ac.uk/projects/fastqc/fastqc_v0.11.8.zip
    - http://download.lab7.io/sources/fastqc_v0.11.8.zip
  md5: bdaf3b9fe957681b3a12349fdfa1c6c0
  patches:
    - bin-path.patch

build:
  number: 0
  script_env:
    - BB_ARCH_FLAGS
    - BB_OPT_FLAGS
    - BB_MAKE_JOBS

test:
  files:
    - test.fq.gz
  commands:
    - fastqc -h

about:
  home: "http://www.bioinformatics.babraham.ac.uk/projects/download.html#fastqc"
  license: GPLv3
  license_file: LICENSE.txt
  summary: "Java quality control application for high throughput sequence data"
