package:
  name: "plink"
  version: "1.90p"

build:
  number: 1

source:
  url: file:///gpfs/gpfs_4mb/rchen/Power9/NGS-App/sources/biobuilds/plink/plink-1.9.tar.gz
  sha256: cfd30ef83990987198e45606d5701fb1f99f4332df16e1e0443945a695073e5c 
#  url: https://github.com/chrchang/plink-ng/archive/b15c19f.tar.gz
#  sha256: e00ef16ac5abeb6b4c4d77846bd655fafc62669fbebf8cd2e941f07b3111907e

requirements:
  build:
  host:
#    - zlib
  run:
#    - zlib

test:
  commands:
    - plink --help | grep "PLINK v1.90p"

about:
  home: https://www.cog-genomics.org/plink2
  license: GPL
  license_file: LICENSE
  summary: Whole genome association analysis toolset, designed to perform a range of basic, large-scale analyses in a computationally efficient manner.
