{% set version = "1.42.2" %}
{% set name = "rtracklayer" %}
{% set bioc = "3.8" %}

package:
  name: 'bioconductor-{{ name|lower }}'
  version: '{{ version }}'
source:
  url:
    - 'https://bioconductor.org/packages/{{ bioc }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz'
  md5: b2748aa591c80c01d6b8fb940fc0a44f
build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/
# Suggests: BSgenome (>= 1.33.4), humanStemCell, microRNA (>= 1.1.1), genefilter, limma, org.Hs.eg.db, hgu133plus2.db, GenomicFeatures, BSgenome.Hsapiens.UCSC.hg19, TxDb.Hsapiens.UCSC.hg19.knownGene, RUnit
requirements:
  host:
    - 'bioconductor-biocgenerics >=0.28.0,<0.31.0'
    - 'bioconductor-biostrings >=2.50.0,<2.53.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.21.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.21.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.37.0'
    - 'bioconductor-iranges >=2.16.0,<2.19.0'
    - 'bioconductor-rsamtools >=1.34.0,<2.1.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.23.0'
    - 'bioconductor-xvector >=0.22.0,<0.25.0'
    - 'bioconductor-zlibbioc >=1.28.0,<1.31.0'
    - r-base=3.6.1
    - 'r-rcurl >=1.95_4'
    - 'r-xml >=3.98-0'
  run:
    - 'bioconductor-biocgenerics >=0.28.0,<0.31.0'
    - 'bioconductor-biostrings >=2.50.0,<2.53.0'
    - 'bioconductor-genomeinfodb >=1.18.0,<1.21.0'
    - 'bioconductor-genomicalignments >=1.18.0,<1.21.0'
    - 'bioconductor-genomicranges >=1.34.0,<1.37.0'
    - 'bioconductor-iranges >=2.16.0,<2.19.0'
    - 'bioconductor-rsamtools >=1.34.0,<2.1.0'
    - 'bioconductor-s4vectors >=0.20.0,<0.23.0'
    - 'bioconductor-xvector >=0.22.0,<0.25.0'
    - 'bioconductor-zlibbioc >=1.28.0,<1.31.0'
    - r-base=3.6.1
    - 'r-rcurl >=1.95_4'
    - 'r-xml >=3.98-0'
  build:
    - automake
    - make
test:
  commands:
    - '$R -e "library(''{{ name }}'')"'
about:
  home: 'https://bioconductor.org/packages/{{ bioc }}/bioc/html/{{ name }}.html'
  license: 'Artistic-2.0 + file LICENSE'
  summary: 'Extensible framework for interacting with multiple genome browsers (currently UCSC built-in) and manipulating annotation tracks in various formats (currently GFF, BED, bedGraph, BED15, WIG, BigWig and 2bit built-in). The user may export/import tracks to/from the supported browsers, as well as query and modify the browser state, such as the current viewport.'
extra:
  identifiers:
    - biotools:rtracklayer
  parent_recipe:
    name: bioconductor-rtracklayer
    path: recipes/bioconductor-rtracklayer
    version: 1.40.6

