package:
  name: perl-io-stringy
  version: "2.111"

source:
  url: https://cpan.metacpan.org/authors/id/D/DS/DSKOLL/IO-stringy-2.111.tar.gz
  md5: e91acf0a800b190d13585a47de775bdd

build:
  noarch: generic
  number: 1

requirements:
  host:
    - perl==5.26.2

  run:
    - perl==5.26.2

test:
  # Perl 'use' tests
  imports:
    - IO::AtomicFile
    - IO::InnerFile
    - IO::Lines
    - IO::Scalar
    - IO::ScalarArray
    - IO::Stringy
    - IO::Wrap
    - IO::WrapTie

about:
  home: http://metacpan.org/pod/IO-stringy
  license: unknown
  summary: 'write a file which is updated atomically'
