{% set name = 'RCurl' %}
{% set version = '1.95-4.11' %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
  sha256: "792a091cf5b80c460d98ed80fe1cad5d9406d0afc32e466e970ee4d2f68c97bf"

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - r-base {{ r_base }}
    - autoconf
    - automake
    - pkg-config
    - r-bitops

  run:
    - r-base
    - r-bitops

test:
  commands:
    - R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: http://www.omegahat.net/RCurl
  license: BSD
  summary: General network (http/ftp/etc.) client interface for R
  description: |
    A wrapper for 'libcurl'. Provides functions to allow one to compose general
    HTTP requests and provides convenient functions to fetch URIs, get & post
    forms, etc. and process the results returned by the Web server.


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: RCurl
# Version: 1.95-4.8
# Title: General Network (HTTP/FTP/...) Client Interface for R
# Author: Duncan Temple Lang and the CRAN team
# SystemRequirements: GNU make, libcurl
# Maintainer: Duncan Temple Lang <duncan@r-project.org>
# Description: A wrapper for 'libcurl' <http://curl.haxx.se/libcurl/> Provides functions to allow one to compose general HTTP requests and provides convenient functions to fetch URIs, get & post forms, etc. and process the results returned by the Web server. This provides a great deal of control over the HTTP/FTP/... connection and the form of the request while providing a higher-level interface than is available just using R socket connections.  Additionally, the underlying implementation is robust and extensive, supporting FTP/FTPS/TFTP (uploads and downloads), SSL/HTTPS, telnet, dict, ldap, and also supports cookies, redirects, authentication, etc.
# License: BSD
# Depends: R (>= 3.0.0), methods, bitops
# Suggests: Rcompression, XML
# URL: http://www.omegahat.net/RCurl
# Additional_repositories: http://www.omegahat.net/R/
# Limitations: One doesn't yet have full control over the contents of a POST form such as specifying files, content type. Error handling uses a single global variable at present.
# Note: This will be used generally to communicate with HTTP servers and specifically in the SOAP package, HTML forms and for accessing data on Web sites that require more state information than simply URL access (e.g. cookies).
# Check: To run R CMD check, one really needs network access. It is an HTTP client! This can be problematic as a Web site may be down when you run but the real tests are important.
# Collate: aclassesEnums.R bitClasses.R xbits.R base64.R binary.S classes.S curl.S curlAuthConstants.R curlEnums.R curlError.R curlInfo.S dynamic.R form.S getFormParams.R getURLContent.R header.R http.R httpError.R httpErrors.R iconv.R info.S mime.R multi.S options.S scp.R support.S upload.R urlExists.R zclone.R zzz.R
# NeedsCompilation: yes
# Packaged: 2016-03-01 07:37:59 UTC; ripley
# Repository: CRAN
# Date/Publication: 2016-03-01 10:54:28
#----------------------------------------------------------------------
