{% set name = "zlibbioc" %}
{% set version = "1.28.0" %}
{% set bioc_version = "3.8" %}

package:
  name: "bioconductor-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "bioconductor-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "https://bioconductor.org/packages/{{ bioc_version }}/bioc/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "50d0611fb97f34409bbedc18f7286de4b319c5c4813101a65567a94984ff5b2e"

requirements:
  build:
    - r-base {{ r_base }}
  run:
    - r-base

build:
  number: 0
  rpaths:
    - lib/R/lib/
    - lib/

test:
  commands:
    - $R -e "library('{{ name }}')"           # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\""  # [win]

about:
  home: "https://bioconductor.org/packages/release/bioc/html/{{ name }}.html"
  license: Artistic 2.0
  summary: An R packaged zlib-1.2.5
