{% set version="1.10.2" %}

package:
  name: bcftools
  version: {{ version }}

build:
  number: 2

source:
  url: https://github.com/samtools/bcftools/releases/download/{{ version }}/bcftools-{{ version }}.tar.bz2
  sha256: f57301869d0055ce3b8e26d8ad880c0c1989bf25eaec8ea5db99b60e31354e2c

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - bzip2
    - htslib ==1.10.2
    - gsl ==2.5
    - curl
    - xz
    - zlib
    - libdeflate
  run:
    # Currently removed due to size and dependency issues
    #- matplotlib # for plot-vcfstats
    #- tectonic # for plot-vcfstats
    - gsl ==2.5
    - htslib ==1.10.2
    - curl
    - perl ==5.26.2
    - libdeflate

test:
  commands:
    - bcftools -h
    - bcftools --version
    - bcftools plugin -lv
#    - plot-vcfstats -h 2>&1 | grep -q "Plots output of "

about:
  home: https://github.com/samtools/bcftools
  license: MIT
  summary: BCFtools is a set of utilities that manipulate variant calls in the Variant
    Call Format (VCF) and its binary counterpart BCF. All commands work transparently
    with both VCFs and BCFs, both uncompressed and BGZF-compressed.  Most commands
    accept VCF, bgzipped VCF and BCF with filetype detected automatically even when
    streaming from a pipe. Indexed VCF and BCF will work in all situations. Un-indexed
    VCF and BCF and streams will work in most, but not all situations.

extra:
  identifiers:
    - biotools:bcftools
    - doi:10.1093/bioinformatics/btp352
