package:
  name: perl-gdtextutil
  version: "0.86"

source:
  url: http://cpan.metacpan.org/authors/id/M/MV/MVERB/GDTextUtil-0.86.tar.gz
  md5: 941ad06eadc86b47f3a32da405665c41

build:
  number: 5

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - perl==5.26.2
    - perl-gd
  run:
    - perl==5.26.2
    - perl-gd

test:
  imports:
    - GD::Text

about:
  home: http://metacpan.org/pod/GDTextUtil
  license: unknown
  summary: 'Text utilities for use with GD'
