{% set name = "caTools" %}
{% set version = "1.17.1" %}

package:
  name: "r-{{ name|lower }}"
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-{{ name|lower }}_{{ version }}.tar.gz"
  url:
    - "http://cran.r-project.org/src/contrib/{{ name }}_{{ version }}.tar.gz"
    - "http://cran.r-project.org/src/contrib/Archive/{{ name }}/{{ name }}_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-{{ name|lower }}_{{ version }}.tar.gz"
  sha256: "d32a73febf00930355cc00f3e4e71357412e0f163faae6a4bf7f552cacfe9af4"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  detect_binary_files_with_prefix: true

# Suggests: MASS, rpart
requirements:
  build:
    - r-base {{ r_base }}
    - r-bitops

  run:
    - r-base
    - r-bitops

test:
  commands:
    - R -e "library('{{ name }}')"          # [not win]
    - "\"%R%\" -e \"library('{{ name }}')\"" # [win]

about:
  home: https://CRAN.R-project.org/package=caTools
  license: GPLv3
  summary: 'Various utility functions window statistic functions, fast AUC calculations, LogitBoost classifier, etc.'


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: caTools
# Type: Package
# Title: Tools: moving window statistics, GIF, Base64, ROC AUC, etc.
# Version: 1.17.1
# Date: 2014-04-21
# Author: Jarek Tuszynski <jaroslaw.w.tuszynski@saic.com>
# Maintainer: Harutyun Khachatryan <kh_harut@yahoo.com>
# Depends: R (>= 2.2.0)
# Imports: bitops
# Suggests: MASS, rpart
# Description: Contains several basic utility functions including: moving (rolling, running) window statistic functions, read/write for GIF and ENVI binary files, fast calculation of AUC, LogitBoost classifier, base64 encoder/decoder, round-off-error-free sum and cumsum, etc.
# License: GPL-3
# Packaged: 2014-09-09 21:05:06 UTC; ripley
# NeedsCompilation: yes
# Repository: CRAN
# Date/Publication: 2014-09-10 16:22:53
#----------------------------------------------------------------------
