site_name: csvtk - CSV/TSV Toolkit
pages:
- Home: index.md
- Download: download.md
- Usage: usage.md
- Tutorial: tutorial.md
- 中文介绍: chinese.md
- More tools: https://github.com/shenwei356

# theme: cinder

theme:
    name: 'material'
    palette:
        primary: 'light blue'
        accent: 'light blue'
    logo:
        icon: 'school'
    favicon: 'files/favicon.ico'
    feature:
        tabs: false
extra:
  manifest: 'manifest.webmanifest'
  
repo_url: https://github.com/shenwei356/csvtk
site_description: csvtk - CSV/TSV toolkit
site_author: shenwei356
google_analytics: ['UA-28948626-9', 'bioinf.shenwei.me/csvtk']
