package:
  name: rsem
  version: "1.3.2"

requirements:
  build:
    - biobuilds-build

    # Need the Anaconda compilers regardless of toolchain we're using to
    # properly compile the R packages (since the BioBuilds "r-base" package was
    # built with the Anaconda toolchain).

    - htslib {{ htslib }}
    - samtools

    # Use BioBuilds Boost package instead of one from 'default' channel
    # to ensure consistency across all the platforms we support.
    - boost {{ boost }}

    - r-base {{ r_base }}
    # Needed by the pRSEM component
    - r-catools >=1.17.1
    - r-data.table >=1.9.6
    - bioconductor-genomicranges >=1.24.3
    - bioconductor-shortread >=1.30.0

  run:
    - samtools
    - perl >=5.0,<6.0
    - python
    - r-base
    # Needed by the EBSeq component
    - bioconductor-ebseq >=1.2.0
    # Needed by the pRSEM component
    - r-catools >=1.17.1
    - r-data.table >=1.9.6
    - bioconductor-genomicranges >=1.24.3
    - bioconductor-shortread >=1.30.0

source:
  fn: "rsem-1.3.2.tar.gz"
  url:
    - "https://github.com/deweylab/RSEM/archive/v1.3.2.tar.gz"
    - "http://download.lab7.io/sources/rsem-1.3.2.tar.gz"
  md5: '48faa4846a9a6de4c9d7cd977e43fc10'
  patches:
    - 01_fix_cxx_11.patch
    - 02_fix_makefile.patch
    - 05_ebseq-install.patch
    - 06_prsem_makefile.patch
    - 04_r-spp-gnu_cxx-namespace.patch 

build:
  number: 2
  features:
    - opt                       # [toolchain != 'default']
  skip_compile_pyc:
    - libexec/{{ environ['PKG_NAME'] }}/pRSEM/*.py

test:
  commands:
    - rsem-prepare-reference 2>&1 | grep reference_name > /dev/null
    - rsem-for-ebseq-find-DE 2>&1 | grep Usage > /dev/null
    - rsem-bam2wig foo bar foobar 2>&1 | grep "Failed to open file" > /dev/null
#    - which rsem-for-ebseq-calculate-clustering-info

about:
  home: "http://deweylab.github.io/RSEM/"
  license: GPLv3
  license_file: COPYING
  summary: "Accurate quantification of gene and isoform expression from RNA-Seq data"

extra:
  notes: >
    The pRSEM component is *NOT* functional out of the box. It requires the
    UCSC `bigWigSummary` application, which we cannot re-distribute due to
    licensing restrictions. To get pRSEM working, you must first download
    `bigWigSummary` for your platform (x86_64 OS X or x86_64 Linux) from
    <http://hgdownload.soe.ucsc.edu/admin/exe/> and install it into the correct
    conda environment's (e.g., BioBuilds) "bin" directory. WARNING: you, the
    end user, accept responsibility for being compliant with the UCSC Genome
    Browser utilities license, as described in the "Source & Utilities
    Downloads" section of <http://hgdownload.cse.ucsc.edu/downloads.html>.
