{% set version = "2.23-15" %}
package:
  name: r-kernsmooth
  version: "{{ version|replace('-', '_') }}"

source:
  fn: "r-kernsmooth_{{ version }}.tar.gz"
  url:
    - "https://cran.r-project.org/src/contrib/KernSmooth_{{ version }}.tar.gz"
    - "https://cran.r-project.org/src/contrib/Archive/KernSmooth/KernSmooth_{{ version }}.tar.gz"
    - "http://download.lab7.io/sources/r-kernsmooth_{{ version }}.tar.gz"
  sha256: "8b72d23ed121a54af188b2cda4441e3ce2646359309885f6455b82c0275210f6"

build:
  number: 1
  rpaths:
    - lib/R/lib/
    - lib/
  # Needed to ensure $PREFIX is long enough that patchelf doesn't change the
  # size of the .so file(s), as changing the size of compiled R libraries
  # triggers "ELF load command alignment not page-aligned" errors on ppc64le.
  detect_binary_files_with_prefix: true

requirements:
  build:
    - r-base {{ r_base }}
  run:
    - r-base

test:
  commands:
    - R -e "library('KernSmooth')" # [not win]

about:
  license: Unlimited
  summary: "Functions for kernel smoothing (and density estimation)"


#----------------------------------------------------------------------
# The original CRAN metadata for this package was:
#
# Package: KernSmooth
# Priority: recommended
# Version: 2.23-15
# Date: 2015-06-29
# Title: Functions for Kernel Smoothing Supporting Wand & Jones (1995)
# Authors@R: c(person("Matt", "Wand", role = "aut", email = "Matt.Wand@uts.edu.au"), person("Brian", "Ripley", role = c("trl", "cre", "ctb"), email = "ripley@stats.ox.ac.uk", comment = "R port and updates"))
# Depends: R (>= 2.5.0), stats
# Suggests: MASS
# Description: Functions for kernel smoothing (and density estimation) corresponding to the book:  Wand, M.P. and Jones, M.C. (1995) "Kernel Smoothing".
# License: Unlimited
# ByteCompile: yes
# NeedsCompilation: yes
# Packaged: 2015-06-29 08:37:00 UTC; ripley
# Author: Matt Wand [aut], Brian Ripley [trl, cre, ctb] (R port and updates)
# Maintainer: Brian Ripley <ripley@stats.ox.ac.uk>
# Repository: CRAN
# Date/Publication: 2015-06-29 17:15:14
#----------------------------------------------------------------------
