package:
    name: tiddit
    version: 2.7.1
source:
    sha256: 1d014cd2d4e1f5410e9ffbeda7a0512d65895ec38d57e8aed5dffa19f32f4699
    url: https://github.com/SciLifeLab/TIDDIT/archive/TIDDIT-2.7.1.tar.gz
build:
    number: '2'
    string: py27_2
requirements:
    build:
        - {{ compiler('cxx') }}
        - {{ compiler('c') }}
        - bzip2 1.0.8
        - ca-certificates 2019.6.16 hecc5488_0
        - cmake 3.15.0 
        - curl 7.65.3
        - expat 2.2.5
        - krb5 1.16.3
        - libcurl 7.65.3
        - libedit 3.1.20170329 hf8c457e_1001
        - libssh2 1.8.2 
        - libuv 1.30.1
        - ncurses 6.1
        - openssl 1.1.1c
        - rhash 1.3.6
        - tk 8.6.9
        - xz 5.2.4
        - zlib 1.2.11
    host:
        - bzip2 1.0.8
        - ca-certificates 2019.6.16 hecc5488_0
        - certifi 2019.6.16 py27_1 
        - cmake 3.15.0
        - curl 7.65.3
        - cython 0.29.13 py27hb209c28_0
        - expat 2.2.5
        - krb5 1.16.3
        - libopenblas 0.3.2 h9ac9557_1
        - libcurl 7.65.3
        - libedit 3.1.20170329
        - libffi 3.2.1
        - libssh2 1.8.2
        - libuv 1.30.1
        - ncurses 6.1
        - numpy 1.15.0 py27h2aefc1b_0
        - openssl 1.1.1c
        - pip 19.2.1 py27_0
        - python 2.7.15
        - readline 8.0
        - rhash 1.3.6
        - setuptools 41.0.1 py27_0
        - sqlite 3.29.0
        - tk 8.6.9
        - wheel 0.33.4 py27_0
        - xz 5.2.4
        - zlib 1.2.11
    run:
        - cmake
        - libgcc-ng >=7.3.0
        - libstdcxx-ng >=7.3.0
#        - numpy
#        - pysam 
#        - python >=2.7,<2.8.0a0
test:
    commands:
        - tiddit >/dev/null
about:
    home: https://github.com/SciLifeLab/TIDDIT
    license: GPL-3
    license_file: LICENSE
    summary: TIDDIT - structural variant calling.
extra:
    copy_test_source_files: true
    final: true
